{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "name": "他社使用ツール調査.ipynb",
      "provenance": [],
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/kenkono5/analytics_competitor_tools/blob/master/%E4%BB%96%E7%A4%BE%E4%BD%BF%E7%94%A8%E3%83%84%E3%83%BC%E3%83%AB%E8%AA%BF%E6%9F%BB.ipynb\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "7wEtWN1QHLAN",
        "colab_type": "code",
        "colab": {
          "resources": {
            "http://localhost:8080/nbextensions/google.colab/files.js": {
              "data": "Ly8gQ29weXJpZ2h0IDIwMTcgR29vZ2xlIExMQwovLwovLyBMaWNlbnNlZCB1bmRlciB0aGUgQXBhY2hlIExpY2Vuc2UsIFZlcnNpb24gMi4wICh0aGUgIkxpY2Vuc2UiKTsKLy8geW91IG1heSBub3QgdXNlIHRoaXMgZmlsZSBleGNlcHQgaW4gY29tcGxpYW5jZSB3aXRoIHRoZSBMaWNlbnNlLgovLyBZb3UgbWF5IG9idGFpbiBhIGNvcHkgb2YgdGhlIExpY2Vuc2UgYXQKLy8KLy8gICAgICBodHRwOi8vd3d3LmFwYWNoZS5vcmcvbGljZW5zZXMvTElDRU5TRS0yLjAKLy8KLy8gVW5sZXNzIHJlcXVpcmVkIGJ5IGFwcGxpY2FibGUgbGF3IG9yIGFncmVlZCB0byBpbiB3cml0aW5nLCBzb2Z0d2FyZQovLyBkaXN0cmlidXRlZCB1bmRlciB0aGUgTGljZW5zZSBpcyBkaXN0cmlidXRlZCBvbiBhbiAiQVMgSVMiIEJBU0lTLAovLyBXSVRIT1VUIFdBUlJBTlRJRVMgT1IgQ09ORElUSU9OUyBPRiBBTlkgS0lORCwgZWl0aGVyIGV4cHJlc3Mgb3IgaW1wbGllZC4KLy8gU2VlIHRoZSBMaWNlbnNlIGZvciB0aGUgc3BlY2lmaWMgbGFuZ3VhZ2UgZ292ZXJuaW5nIHBlcm1pc3Npb25zIGFuZAovLyBsaW1pdGF0aW9ucyB1bmRlciB0aGUgTGljZW5zZS4KCi8qKgogKiBAZmlsZW92ZXJ2aWV3IEhlbHBlcnMgZm9yIGdvb2dsZS5jb2xhYiBQeXRob24gbW9kdWxlLgogKi8KKGZ1bmN0aW9uKHNjb3BlKSB7CmZ1bmN0aW9uIHNwYW4odGV4dCwgc3R5bGVBdHRyaWJ1dGVzID0ge30pIHsKICBjb25zdCBlbGVtZW50ID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnc3BhbicpOwogIGVsZW1lbnQudGV4dENvbnRlbnQgPSB0ZXh0OwogIGZvciAoY29uc3Qga2V5IG9mIE9iamVjdC5rZXlzKHN0eWxlQXR0cmlidXRlcykpIHsKICAgIGVsZW1lbnQuc3R5bGVba2V5XSA9IHN0eWxlQXR0cmlidXRlc1trZXldOwogIH0KICByZXR1cm4gZWxlbWVudDsKfQoKLy8gTWF4IG51bWJlciBvZiBieXRlcyB3aGljaCB3aWxsIGJlIHVwbG9hZGVkIGF0IGEgdGltZS4KY29uc3QgTUFYX1BBWUxPQURfU0laRSA9IDEwMCAqIDEwMjQ7CgpmdW5jdGlvbiBfdXBsb2FkRmlsZXMoaW5wdXRJZCwgb3V0cHV0SWQpIHsKICBjb25zdCBzdGVwcyA9IHVwbG9hZEZpbGVzU3RlcChpbnB1dElkLCBvdXRwdXRJZCk7CiAgY29uc3Qgb3V0cHV0RWxlbWVudCA9IGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKG91dHB1dElkKTsKICAvLyBDYWNoZSBzdGVwcyBvbiB0aGUgb3V0cHV0RWxlbWVudCB0byBtYWtlIGl0IGF2YWlsYWJsZSBmb3IgdGhlIG5leHQgY2FsbAogIC8vIHRvIHVwbG9hZEZpbGVzQ29udGludWUgZnJvbSBQeXRob24uCiAgb3V0cHV0RWxlbWVudC5zdGVwcyA9IHN0ZXBzOwoKICByZXR1cm4gX3VwbG9hZEZpbGVzQ29udGludWUob3V0cHV0SWQpOwp9CgovLyBUaGlzIGlzIHJvdWdobHkgYW4gYXN5bmMgZ2VuZXJhdG9yIChub3Qgc3VwcG9ydGVkIGluIHRoZSBicm93c2VyIHlldCksCi8vIHdoZXJlIHRoZXJlIGFyZSBtdWx0aXBsZSBhc3luY2hyb25vdXMgc3RlcHMgYW5kIHRoZSBQeXRob24gc2lkZSBpcyBnb2luZwovLyB0byBwb2xsIGZvciBjb21wbGV0aW9uIG9mIGVhY2ggc3RlcC4KLy8gVGhpcyB1c2VzIGEgUHJvbWlzZSB0byBibG9jayB0aGUgcHl0aG9uIHNpZGUgb24gY29tcGxldGlvbiBvZiBlYWNoIHN0ZXAsCi8vIHRoZW4gcGFzc2VzIHRoZSByZXN1bHQgb2YgdGhlIHByZXZpb3VzIHN0ZXAgYXMgdGhlIGlucHV0IHRvIHRoZSBuZXh0IHN0ZXAuCmZ1bmN0aW9uIF91cGxvYWRGaWxlc0NvbnRpbnVlKG91dHB1dElkKSB7CiAgY29uc3Qgb3V0cHV0RWxlbWVudCA9IGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKG91dHB1dElkKTsKICBjb25zdCBzdGVwcyA9IG91dHB1dEVsZW1lbnQuc3RlcHM7CgogIGNvbnN0IG5leHQgPSBzdGVwcy5uZXh0KG91dHB1dEVsZW1lbnQubGFzdFByb21pc2VWYWx1ZSk7CiAgcmV0dXJuIFByb21pc2UucmVzb2x2ZShuZXh0LnZhbHVlLnByb21pc2UpLnRoZW4oKHZhbHVlKSA9PiB7CiAgICAvLyBDYWNoZSB0aGUgbGFzdCBwcm9taXNlIHZhbHVlIHRvIG1ha2UgaXQgYXZhaWxhYmxlIHRvIHRoZSBuZXh0CiAgICAvLyBzdGVwIG9mIHRoZSBnZW5lcmF0b3IuCiAgICBvdXRwdXRFbGVtZW50Lmxhc3RQcm9taXNlVmFsdWUgPSB2YWx1ZTsKICAgIHJldHVybiBuZXh0LnZhbHVlLnJlc3BvbnNlOwogIH0pOwp9CgovKioKICogR2VuZXJhdG9yIGZ1bmN0aW9uIHdoaWNoIGlzIGNhbGxlZCBiZXR3ZWVuIGVhY2ggYXN5bmMgc3RlcCBvZiB0aGUgdXBsb2FkCiAqIHByb2Nlc3MuCiAqIEBwYXJhbSB7c3RyaW5nfSBpbnB1dElkIEVsZW1lbnQgSUQgb2YgdGhlIGlucHV0IGZpbGUgcGlja2VyIGVsZW1lbnQuCiAqIEBwYXJhbSB7c3RyaW5nfSBvdXRwdXRJZCBFbGVtZW50IElEIG9mIHRoZSBvdXRwdXQgZGlzcGxheS4KICogQHJldHVybiB7IUl0ZXJhYmxlPCFPYmplY3Q+fSBJdGVyYWJsZSBvZiBuZXh0IHN0ZXBzLgogKi8KZnVuY3Rpb24qIHVwbG9hZEZpbGVzU3RlcChpbnB1dElkLCBvdXRwdXRJZCkgewogIGNvbnN0IGlucHV0RWxlbWVudCA9IGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKGlucHV0SWQpOwogIGlucHV0RWxlbWVudC5kaXNhYmxlZCA9IGZhbHNlOwoKICBjb25zdCBvdXRwdXRFbGVtZW50ID0gZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQob3V0cHV0SWQpOwogIG91dHB1dEVsZW1lbnQuaW5uZXJIVE1MID0gJyc7CgogIGNvbnN0IHBpY2tlZFByb21pc2UgPSBuZXcgUHJvbWlzZSgocmVzb2x2ZSkgPT4gewogICAgaW5wdXRFbGVtZW50LmFkZEV2ZW50TGlzdGVuZXIoJ2NoYW5nZScsIChlKSA9PiB7CiAgICAgIHJlc29sdmUoZS50YXJnZXQuZmlsZXMpOwogICAgfSk7CiAgfSk7CgogIGNvbnN0IGNhbmNlbCA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2J1dHRvbicpOwogIGlucHV0RWxlbWVudC5wYXJlbnRFbGVtZW50LmFwcGVuZENoaWxkKGNhbmNlbCk7CiAgY2FuY2VsLnRleHRDb250ZW50ID0gJ0NhbmNlbCB1cGxvYWQnOwogIGNvbnN0IGNhbmNlbFByb21pc2UgPSBuZXcgUHJvbWlzZSgocmVzb2x2ZSkgPT4gewogICAgY2FuY2VsLm9uY2xpY2sgPSAoKSA9PiB7CiAgICAgIHJlc29sdmUobnVsbCk7CiAgICB9OwogIH0pOwoKICAvLyBXYWl0IGZvciB0aGUgdXNlciB0byBwaWNrIHRoZSBmaWxlcy4KICBjb25zdCBmaWxlcyA9IHlpZWxkIHsKICAgIHByb21pc2U6IFByb21pc2UucmFjZShbcGlja2VkUHJvbWlzZSwgY2FuY2VsUHJvbWlzZV0pLAogICAgcmVzcG9uc2U6IHsKICAgICAgYWN0aW9uOiAnc3RhcnRpbmcnLAogICAgfQogIH07CgogIGNhbmNlbC5yZW1vdmUoKTsKCiAgLy8gRGlzYWJsZSB0aGUgaW5wdXQgZWxlbWVudCBzaW5jZSBmdXJ0aGVyIHBpY2tzIGFyZSBub3QgYWxsb3dlZC4KICBpbnB1dEVsZW1lbnQuZGlzYWJsZWQgPSB0cnVlOwoKICBpZiAoIWZpbGVzKSB7CiAgICByZXR1cm4gewogICAgICByZXNwb25zZTogewogICAgICAgIGFjdGlvbjogJ2NvbXBsZXRlJywKICAgICAgfQogICAgfTsKICB9CgogIGZvciAoY29uc3QgZmlsZSBvZiBmaWxlcykgewogICAgY29uc3QgbGkgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdsaScpOwogICAgbGkuYXBwZW5kKHNwYW4oZmlsZS5uYW1lLCB7Zm9udFdlaWdodDogJ2JvbGQnfSkpOwogICAgbGkuYXBwZW5kKHNwYW4oCiAgICAgICAgYCgke2ZpbGUudHlwZSB8fCAnbi9hJ30pIC0gJHtmaWxlLnNpemV9IGJ5dGVzLCBgICsKICAgICAgICBgbGFzdCBtb2RpZmllZDogJHsKICAgICAgICAgICAgZmlsZS5sYXN0TW9kaWZpZWREYXRlID8gZmlsZS5sYXN0TW9kaWZpZWREYXRlLnRvTG9jYWxlRGF0ZVN0cmluZygpIDoKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgJ24vYSd9IC0gYCkpOwogICAgY29uc3QgcGVyY2VudCA9IHNwYW4oJzAlIGRvbmUnKTsKICAgIGxpLmFwcGVuZENoaWxkKHBlcmNlbnQpOwoKICAgIG91dHB1dEVsZW1lbnQuYXBwZW5kQ2hpbGQobGkpOwoKICAgIGNvbnN0IGZpbGVEYXRhUHJvbWlzZSA9IG5ldyBQcm9taXNlKChyZXNvbHZlKSA9PiB7CiAgICAgIGNvbnN0IHJlYWRlciA9IG5ldyBGaWxlUmVhZGVyKCk7CiAgICAgIHJlYWRlci5vbmxvYWQgPSAoZSkgPT4gewogICAgICAgIHJlc29sdmUoZS50YXJnZXQucmVzdWx0KTsKICAgICAgfTsKICAgICAgcmVhZGVyLnJlYWRBc0FycmF5QnVmZmVyKGZpbGUpOwogICAgfSk7CiAgICAvLyBXYWl0IGZvciB0aGUgZGF0YSB0byBiZSByZWFkeS4KICAgIGxldCBmaWxlRGF0YSA9IHlpZWxkIHsKICAgICAgcHJvbWlzZTogZmlsZURhdGFQcm9taXNlLAogICAgICByZXNwb25zZTogewogICAgICAgIGFjdGlvbjogJ2NvbnRpbnVlJywKICAgICAgfQogICAgfTsKCiAgICAvLyBVc2UgYSBjaHVua2VkIHNlbmRpbmcgdG8gYXZvaWQgbWVzc2FnZSBzaXplIGxpbWl0cy4gU2VlIGIvNjIxMTU2NjAuCiAgICBsZXQgcG9zaXRpb24gPSAwOwogICAgd2hpbGUgKHBvc2l0aW9uIDwgZmlsZURhdGEuYnl0ZUxlbmd0aCkgewogICAgICBjb25zdCBsZW5ndGggPSBNYXRoLm1pbihmaWxlRGF0YS5ieXRlTGVuZ3RoIC0gcG9zaXRpb24sIE1BWF9QQVlMT0FEX1NJWkUpOwogICAgICBjb25zdCBjaHVuayA9IG5ldyBVaW50OEFycmF5KGZpbGVEYXRhLCBwb3NpdGlvbiwgbGVuZ3RoKTsKICAgICAgcG9zaXRpb24gKz0gbGVuZ3RoOwoKICAgICAgY29uc3QgYmFzZTY0ID0gYnRvYShTdHJpbmcuZnJvbUNoYXJDb2RlLmFwcGx5KG51bGwsIGNodW5rKSk7CiAgICAgIHlpZWxkIHsKICAgICAgICByZXNwb25zZTogewogICAgICAgICAgYWN0aW9uOiAnYXBwZW5kJywKICAgICAgICAgIGZpbGU6IGZpbGUubmFtZSwKICAgICAgICAgIGRhdGE6IGJhc2U2NCwKICAgICAgICB9LAogICAgICB9OwogICAgICBwZXJjZW50LnRleHRDb250ZW50ID0KICAgICAgICAgIGAke01hdGgucm91bmQoKHBvc2l0aW9uIC8gZmlsZURhdGEuYnl0ZUxlbmd0aCkgKiAxMDApfSUgZG9uZWA7CiAgICB9CiAgfQoKICAvLyBBbGwgZG9uZS4KICB5aWVsZCB7CiAgICByZXNwb25zZTogewogICAgICBhY3Rpb246ICdjb21wbGV0ZScsCiAgICB9CiAgfTsKfQoKc2NvcGUuZ29vZ2xlID0gc2NvcGUuZ29vZ2xlIHx8IHt9OwpzY29wZS5nb29nbGUuY29sYWIgPSBzY29wZS5nb29nbGUuY29sYWIgfHwge307CnNjb3BlLmdvb2dsZS5jb2xhYi5fZmlsZXMgPSB7CiAgX3VwbG9hZEZpbGVzLAogIF91cGxvYWRGaWxlc0NvbnRpbnVlLAp9Owp9KShzZWxmKTsK",
              "ok": true,
              "headers": [
                [
                  "content-type",
                  "application/javascript"
                ]
              ],
              "status": 200,
              "status_text": ""
            }
          },
          "base_uri": "https://localhost:8080/",
          "height": 1000
        },
        "outputId": "d45ed648-283e-40bf-9d84-96b16d710f9c"
      },
      "source": [
        "import requests\n",
        "from bs4 import BeautifulSoup as bs\n",
        "from time import sleep\n",
        "\n",
        "from google.colab import files\n",
        "uploaded = files.upload()\n",
        "\n",
        "import pandas as pd\n",
        "\n",
        "# df = pandas.read_excel('test.xlsx', sheet_name=0)\n",
        "# df.to_csv('test.csv', index=False)\n",
        "\n",
        "df= pd.read_csv('./①FUMA_東京_小売全般_マスターデータ.csv', encoding=\"utf_8\")\n",
        "df.head()\n",
        "\n",
        "array = df.values\n",
        "company_name_list = []\n",
        "url_list = []\n",
        "\n",
        "pardot_list = []\n",
        "eloqua_list = []\n",
        "marketo_list = []\n",
        "urlNG_list = []\n",
        "num = 1\n",
        "for value in array:\n",
        "  company_name_list.append(value[3])\n",
        "  url_list.append(value[4])\n",
        "\n",
        "for i, j in zip(url_list, company_name_list):\n",
        "  try:\n",
        "    res = requests.get(i, timeout=10)\n",
        "    print(num)\n",
        "  except Exception as e: \n",
        "    pass\n",
        "    print(\"=== エラー内容 始 ===\")\n",
        "    print(\"type:\" + str(type(e)))\n",
        "    print(\"args:\" + str(e.args))\n",
        "    print(\"e自身:\" + str(e))\n",
        "    print(\"=== エラー内容 完 ===\")\n",
        "    urlNG_list.append(j)\n",
        "    print(num, \"pass!\") \n",
        "  soup = bs(res.text, 'html.parser')\n",
        "  script_tag = soup.find_all('script')\n",
        "  num += 1\n",
        "  for script in script_tag:\n",
        "    if \"pardot\" in script.text:\n",
        "      pardot_list.append(j)\n",
        "\n",
        "    if \"elqQ\" in script.text:\n",
        "      eloqua_list.append(j)\n",
        "\n",
        "    if \"marketo\" in script.text:\n",
        "      marketo_list.append(j)\n",
        "\n",
        "print(pardot_list)\n",
        "print(eloqua_list)\n",
        "print(marketo_list)\n",
        "print(urlNG_list)\n",
        "\n",
        "use_pardot = []\n",
        "use_eloqua = []\n",
        "use_marketo = []\n",
        "ng_url = []\n",
        "for value in array:\n",
        "  if value[3] in pardot_list:\n",
        "    use_pardot.append(1)\n",
        "  else:\n",
        "    use_pardot.append(0)\n",
        "\n",
        "  if value[3] in eloqua_list:\n",
        "    use_eloqua.append(1)\n",
        "  else:\n",
        "    use_eloqua.append(0)\n",
        "\n",
        "  if value[3] in marketo_list:\n",
        "    use_marketo.append(1)\n",
        "  else:\n",
        "    use_marketo.append(0)\n",
        "\n",
        "  if value[3] in urlNG_list:\n",
        "    ng_url.append(1)\n",
        "  else:\n",
        "    ng_url.append(0)\n",
        "\n",
        "df['pardot'] = use_pardot\n",
        "df['eloqua'] = use_eloqua\n",
        "df['marketo'] = use_marketo\n",
        "df['NGURL'] = ng_url\n",
        "df.to_csv(\"./完了①FUMA_東京_小売全般_マスターデータ.csv\", encoding=\"utf_8_sig\")"
      ],
      "execution_count": null,
      "outputs": [
        {
          "output_type": "display_data",
          "data": {
            "text/html": [
              "\n",
              "     <input type=\"file\" id=\"files-aad64483-8bc2-4757-a54c-9416ee553c59\" name=\"files[]\" multiple disabled\n",
              "        style=\"border:none\" />\n",
              "     <output id=\"result-aad64483-8bc2-4757-a54c-9416ee553c59\">\n",
              "      Upload widget is only available when the cell has been executed in the\n",
              "      current browser session. Please rerun this cell to enable.\n",
              "      </output>\n",
              "      <script src=\"/nbextensions/google.colab/files.js\"></script> "
            ],
            "text/plain": [
              "<IPython.core.display.HTML object>"
            ]
          },
          "metadata": {
            "tags": []
          }
        },
        {
          "output_type": "stream",
          "text": [
            "Saving ①FUMA_東京_小売全般_マスターデータ.csv to ①FUMA_東京_小売全般_マスターデータ.csv\n",
            "1\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectTimeout'>\n",
            "args:(MaxRetryError(\"HTTPConnectionPool(host='1957sanpo.co.jp', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f20e5893320>, 'Connection to 1957sanpo.co.jp timed out. (connect timeout=10)'))\",),)\n",
            "e自身:HTTPConnectionPool(host='1957sanpo.co.jp', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f20e5893320>, 'Connection to 1957sanpo.co.jp timed out. (connect timeout=10)'))\n",
            "=== エラー内容 完 ===\n",
            "2 pass!\n",
            "3\n",
            "4\n",
            "5\n",
            "6\n",
            "7\n",
            "8\n",
            "9\n",
            "10\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectTimeout'>\n",
            "args:(MaxRetryError(\"HTTPConnectionPool(host='accoladewines.jp', port=80): Max retries exceeded with url: /home (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f20e5713d30>, 'Connection to accoladewines.jp timed out. (connect timeout=10)'))\",),)\n",
            "e自身:HTTPConnectionPool(host='accoladewines.jp', port=80): Max retries exceeded with url: /home (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f20e5713d30>, 'Connection to accoladewines.jp timed out. (connect timeout=10)'))\n",
            "=== エラー内容 完 ===\n",
            "11 pass!\n",
            "12\n",
            "13\n",
            "14\n",
            "15\n",
            "16\n",
            "17\n",
            "18\n",
            "19\n",
            "20\n",
            "21\n",
            "22\n",
            "23\n",
            "24\n",
            "25\n",
            "26\n",
            "27\n",
            "28\n",
            "29\n",
            "30\n",
            "31\n",
            "32\n",
            "33\n",
            "34\n",
            "35\n",
            "36\n",
            "37\n",
            "38\n",
            "39\n",
            "40\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectionError'>\n",
            "args:(MaxRetryError(\"HTTPConnectionPool(host='alphazeroth.org', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20e553e978>: Failed to establish a new connection: [Errno -2] Name or service not known',))\",),)\n",
            "e自身:HTTPConnectionPool(host='alphazeroth.org', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20e553e978>: Failed to establish a new connection: [Errno -2] Name or service not known',))\n",
            "=== エラー内容 完 ===\n",
            "41 pass!\n",
            "42\n",
            "43\n",
            "44\n",
            "45\n",
            "46\n",
            "47\n",
            "48\n",
            "49\n",
            "50\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectionError'>\n",
            "args:(MaxRetryError(\"HTTPConnectionPool(host='aobax.holy.jp', port=80): Max retries exceeded with url: /aobarentogen/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20e4ff29b0>: Failed to establish a new connection: [Errno -2] Name or service not known',))\",),)\n",
            "e自身:HTTPConnectionPool(host='aobax.holy.jp', port=80): Max retries exceeded with url: /aobarentogen/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20e4ff29b0>: Failed to establish a new connection: [Errno -2] Name or service not known',))\n",
            "=== エラー内容 完 ===\n",
            "51 pass!\n",
            "52\n",
            "53\n",
            "54\n",
            "55\n",
            "56\n",
            "57\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectionError'>\n",
            "args:(MaxRetryError(\"HTTPConnectionPool(host='aqjapan.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20e480ac50>: Failed to establish a new connection: [Errno -2] Name or service not known',))\",),)\n",
            "e自身:HTTPConnectionPool(host='aqjapan.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20e480ac50>: Failed to establish a new connection: [Errno -2] Name or service not known',))\n",
            "=== エラー内容 完 ===\n",
            "58 pass!\n",
            "59\n",
            "60\n",
            "61\n",
            "62\n",
            "63\n",
            "64\n",
            "65\n",
            "66\n",
            "67\n",
            "68\n",
            "69\n",
            "70\n",
            "71\n",
            "72\n",
            "73\n",
            "74\n",
            "75\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectionError'>\n",
            "args:(MaxRetryError(\"HTTPConnectionPool(host='asahi-netshop.asahi-bu.co.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20e48dd748>: Failed to establish a new connection: [Errno -2] Name or service not known',))\",),)\n",
            "e自身:HTTPConnectionPool(host='asahi-netshop.asahi-bu.co.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20e48dd748>: Failed to establish a new connection: [Errno -2] Name or service not known',))\n",
            "=== エラー内容 完 ===\n",
            "76 pass!\n",
            "77\n",
            "78\n",
            "79\n",
            "80\n",
            "81\n",
            "82\n",
            "83\n",
            "84\n",
            "85\n",
            "86\n",
            "87\n",
            "88\n",
            "89\n",
            "90\n",
            "91\n",
            "92\n",
            "93\n",
            "94\n",
            "95\n",
            "96\n",
            "97\n",
            "98\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectionError'>\n",
            "args:(MaxRetryError(\"HTTPConnectionPool(host='balenciaga', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20e4714278>: Failed to establish a new connection: [Errno -2] Name or service not known',))\",),)\n",
            "e自身:HTTPConnectionPool(host='balenciaga', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20e4714278>: Failed to establish a new connection: [Errno -2] Name or service not known',))\n",
            "=== エラー内容 完 ===\n",
            "99 pass!\n",
            "100\n",
            "101\n",
            "102\n",
            "103\n",
            "104\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectionError'>\n",
            "args:(MaxRetryError(\"HTTPConnectionPool(host='bebetokyo.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20e46bcd30>: Failed to establish a new connection: [Errno -2] Name or service not known',))\",),)\n",
            "e自身:HTTPConnectionPool(host='bebetokyo.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20e46bcd30>: Failed to establish a new connection: [Errno -2] Name or service not known',))\n",
            "=== エラー内容 完 ===\n",
            "105 pass!\n",
            "106\n",
            "107\n",
            "108\n",
            "109\n",
            "110\n",
            "111\n",
            "112\n",
            "113\n",
            "114\n",
            "115\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectionError'>\n",
            "args:(MaxRetryError(\"HTTPConnectionPool(host='biotron.co.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20e5847198>: Failed to establish a new connection: [Errno -2] Name or service not known',))\",),)\n",
            "e自身:HTTPConnectionPool(host='biotron.co.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20e5847198>: Failed to establish a new connection: [Errno -2] Name or service not known',))\n",
            "=== エラー内容 完 ===\n",
            "116 pass!\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectionError'>\n",
            "args:(MaxRetryError(\"HTTPConnectionPool(host='biou.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20e54bc978>: Failed to establish a new connection: [Errno -5] No address associated with hostname',))\",),)\n",
            "e自身:HTTPConnectionPool(host='biou.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20e54bc978>: Failed to establish a new connection: [Errno -5] No address associated with hostname',))\n",
            "=== エラー内容 完 ===\n",
            "117 pass!\n",
            "118\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectionError'>\n",
            "args:(MaxRetryError(\"HTTPConnectionPool(host='biz-reborn.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20e4fe0ac8>: Failed to establish a new connection: [Errno -2] Name or service not known',))\",),)\n",
            "e自身:HTTPConnectionPool(host='biz-reborn.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20e4fe0ac8>: Failed to establish a new connection: [Errno -2] Name or service not known',))\n",
            "=== エラー内容 完 ===\n",
            "119 pass!\n",
            "120\n",
            "121\n",
            "122\n",
            "123\n",
            "124\n",
            "125\n",
            "126\n",
            "127\n",
            "128\n",
            "129\n",
            "130\n",
            "131\n",
            "132\n",
            "133\n",
            "134\n",
            "135\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.SSLError'>\n",
            "args:(MaxRetryError('HTTPSConnectionPool(host=\\'byokaneworld.com\\', port=443): Max retries exceeded with url: / (Caused by SSLError(CertificateError(\"hostname \\'byokaneworld.com\\' doesn\\'t match \\'www.byokaneworld.com\\'\",),))',),)\n",
            "e自身:HTTPSConnectionPool(host='byokaneworld.com', port=443): Max retries exceeded with url: / (Caused by SSLError(CertificateError(\"hostname 'byokaneworld.com' doesn't match 'www.byokaneworld.com'\",),))\n",
            "=== エラー内容 完 ===\n",
            "136 pass!\n",
            "137\n",
            "138\n",
            "139\n",
            "140\n",
            "141\n",
            "142\n",
            "143\n",
            "144\n",
            "145\n",
            "146\n",
            "147\n",
            "148\n",
            "149\n",
            "150\n",
            "151\n",
            "152\n",
            "153\n",
            "154\n",
            "155\n",
            "156\n",
            "157\n",
            "158\n",
            "159\n",
            "160\n",
            "161\n",
            "162\n",
            "163\n",
            "164\n",
            "165\n",
            "166\n",
            "167\n",
            "168\n",
            "169\n",
            "170\n",
            "171\n",
            "172\n",
            "173\n",
            "174\n",
            "175\n",
            "176\n",
            "177\n",
            "178\n",
            "179\n",
            "180\n",
            "181\n",
            "182\n",
            "183\n",
            "184\n",
            "185\n",
            "186\n",
            "187\n",
            "188\n",
            "189\n",
            "190\n",
            "191\n",
            "192\n",
            "193\n",
            "194\n",
            "195\n",
            "196\n",
            "197\n",
            "198\n",
            "199\n",
            "200\n",
            "201\n",
            "202\n",
            "203\n",
            "204\n",
            "205\n",
            "206\n",
            "207\n",
            "208\n",
            "209\n",
            "210\n",
            "211\n",
            "212\n",
            "213\n",
            "214\n",
            "215\n",
            "216\n",
            "217\n",
            "218\n",
            "219\n",
            "220\n",
            "221\n",
            "222\n",
            "223\n",
            "224\n",
            "225\n",
            "226\n",
            "227\n",
            "228\n",
            "229\n",
            "230\n",
            "231\n",
            "232\n",
            "233\n",
            "234\n",
            "235\n",
            "236\n",
            "237\n",
            "238\n",
            "239\n",
            "240\n",
            "241\n",
            "242\n",
            "243\n",
            "244\n",
            "245\n",
            "246\n",
            "247\n",
            "248\n",
            "249\n",
            "250\n",
            "251\n",
            "252\n",
            "253\n",
            "254\n",
            "255\n",
            "256\n",
            "257\n",
            "258\n",
            "259\n",
            "260\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectionError'>\n",
            "args:(MaxRetryError(\"HTTPConnectionPool(host='ems-group.co.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20e5124438>: Failed to establish a new connection: [Errno -2] Name or service not known',))\",),)\n",
            "e自身:HTTPConnectionPool(host='ems-group.co.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20e5124438>: Failed to establish a new connection: [Errno -2] Name or service not known',))\n",
            "=== エラー内容 完 ===\n",
            "261 pass!\n",
            "262\n",
            "263\n",
            "264\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectionError'>\n",
            "args:(MaxRetryError(\"HTTPConnectionPool(host='eng.arteria-net.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20e53ca550>: Failed to establish a new connection: [Errno -2] Name or service not known',))\",),)\n",
            "e自身:HTTPConnectionPool(host='eng.arteria-net.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20e53ca550>: Failed to establish a new connection: [Errno -2] Name or service not known',))\n",
            "=== エラー内容 完 ===\n",
            "265 pass!\n",
            "266\n",
            "267\n",
            "268\n",
            "269\n",
            "270\n",
            "271\n",
            "272\n",
            "273\n",
            "274\n",
            "275\n",
            "276\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.SSLError'>\n",
            "args:(MaxRetryError(\"HTTPSConnectionPool(host='escamare.co.jp', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))\",),)\n",
            "e自身:HTTPSConnectionPool(host='escamare.co.jp', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))\n",
            "=== エラー内容 完 ===\n",
            "277 pass!\n",
            "278\n",
            "279\n",
            "280\n",
            "281\n",
            "282\n",
            "283\n",
            "284\n",
            "285\n",
            "286\n",
            "287\n",
            "288\n",
            "289\n",
            "290\n",
            "291\n",
            "292\n",
            "293\n",
            "294\n",
            "295\n",
            "296\n",
            "297\n",
            "298\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectTimeout'>\n",
            "args:(MaxRetryError(\"HTTPSConnectionPool(host='field-one.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f20e5408c18>, 'Connection to field-one.com timed out. (connect timeout=10)'))\",),)\n",
            "e自身:HTTPSConnectionPool(host='field-one.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f20e5408c18>, 'Connection to field-one.com timed out. (connect timeout=10)'))\n",
            "=== エラー内容 完 ===\n",
            "299 pass!\n",
            "300\n",
            "301\n",
            "302\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.SSLError'>\n",
            "args:(MaxRetryError('HTTPSConnectionPool(host=\\'firescue.net\\', port=443): Max retries exceeded with url: / (Caused by SSLError(CertificateError(\"hostname \\'firescue.net\\' doesn\\'t match either of \\'*.sakura.ne.jp\\', \\'*.180r.com\\', \\'*.2-d.jp\\', \\'*.achoo.jp\\', \\'*.amaretto.jp\\', \\'*.bona.jp\\', \\'*.chew.jp\\', \\'*.crap.jp\\', \\'*.daynight.jp\\', \\'*.deko8.jp\\', \\'*.dojin.com\\', \\'*.eek.jp\\', \\'*.flop.jp\\', \\'*.from.tv\\', \\'*.fubuki.info\\', \\'*.gokujou.biz\\', \\'*.grats.jp\\', \\'*.grrr.jp\\', \\'*.halfmoon.jp\\', \\'*.ivory.ne.jp\\', \\'*.jeez.jp\\', \\'*.jpn.org\\', \\'*.kirara.st\\', \\'*.kokage.cc\\', \\'*.mail-box.ne.jp\\', \\'*.matrix.jp\\', \\'*.mimoza.jp\\', \\'*.mints.ne.jp\\', \\'*.mokuren.ne.jp\\', \\'*.nazo.cc\\', \\'*.netgamers.jp\\', \\'*.noob.jp\\', \\'*.nyanta.jp\\', \\'*.o0o0.jp\\', \\'*.opal.ne.jp\\', \\'*.rash.jp\\', \\'*.razor.jp\\', \\'*.rdy.jp\\', \\'*.rgr.jp\\', \\'*.rojo.jp\\', \\'*.rossa.cc\\', \\'*.rulez.jp\\', \\'*.rusk.to\\', \\'*.saikyou.biz\\', \\'*.sakura.tv\\', \\'*.sakuratan.com\\', \\'*.sakuraweb.com\\', \\'*.saloon.jp\\', \\'*.silk.to\\', \\'*.skr.jp\\', \\'*.spawn.jp\\', \\'*.squares.net\\', \\'*.sumomo.ne.jp\\', \\'*.tank.jp\\', \\'*.thyme.jp\\', \\'*.topaz.ne.jp\\', \\'*.uh-oh.jp\\', \\'*.undo.jp\\', \\'*.websozai.jp\\', \\'*.whoa.jp\\', \\'*.x0.com\\', \\'*.x0.to\\', \\'*.xii.jp\\'\",),))',),)\n",
            "e自身:HTTPSConnectionPool(host='firescue.net', port=443): Max retries exceeded with url: / (Caused by SSLError(CertificateError(\"hostname 'firescue.net' doesn't match either of '*.sakura.ne.jp', '*.180r.com', '*.2-d.jp', '*.achoo.jp', '*.amaretto.jp', '*.bona.jp', '*.chew.jp', '*.crap.jp', '*.daynight.jp', '*.deko8.jp', '*.dojin.com', '*.eek.jp', '*.flop.jp', '*.from.tv', '*.fubuki.info', '*.gokujou.biz', '*.grats.jp', '*.grrr.jp', '*.halfmoon.jp', '*.ivory.ne.jp', '*.jeez.jp', '*.jpn.org', '*.kirara.st', '*.kokage.cc', '*.mail-box.ne.jp', '*.matrix.jp', '*.mimoza.jp', '*.mints.ne.jp', '*.mokuren.ne.jp', '*.nazo.cc', '*.netgamers.jp', '*.noob.jp', '*.nyanta.jp', '*.o0o0.jp', '*.opal.ne.jp', '*.rash.jp', '*.razor.jp', '*.rdy.jp', '*.rgr.jp', '*.rojo.jp', '*.rossa.cc', '*.rulez.jp', '*.rusk.to', '*.saikyou.biz', '*.sakura.tv', '*.sakuratan.com', '*.sakuraweb.com', '*.saloon.jp', '*.silk.to', '*.skr.jp', '*.spawn.jp', '*.squares.net', '*.sumomo.ne.jp', '*.tank.jp', '*.thyme.jp', '*.topaz.ne.jp', '*.uh-oh.jp', '*.undo.jp', '*.websozai.jp', '*.whoa.jp', '*.x0.com', '*.x0.to', '*.xii.jp'\",),))\n",
            "=== エラー内容 完 ===\n",
            "303 pass!\n",
            "304\n",
            "305\n",
            "306\n",
            "307\n",
            "308\n",
            "309\n",
            "310\n",
            "311\n",
            "312\n",
            "313\n",
            "314\n",
            "315\n",
            "316\n",
            "317\n",
            "318\n",
            "319\n",
            "320\n",
            "321\n",
            "322\n",
            "323\n",
            "324\n",
            "325\n",
            "326\n",
            "327\n",
            "328\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectionError'>\n",
            "args:(MaxRetryError(\"HTTPConnectionPool(host='fuji-micro.co.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20e5651550>: Failed to establish a new connection: [Errno -2] Name or service not known',))\",),)\n",
            "e自身:HTTPConnectionPool(host='fuji-micro.co.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20e5651550>: Failed to establish a new connection: [Errno -2] Name or service not known',))\n",
            "=== エラー内容 完 ===\n",
            "329 pass!\n",
            "330\n",
            "331\n",
            "332\n",
            "333\n",
            "334\n",
            "335\n",
            "336\n",
            "337\n",
            "338\n",
            "339\n",
            "340\n",
            "341\n",
            "342\n",
            "343\n",
            "344\n",
            "345\n",
            "346\n",
            "347\n",
            "348\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectionError'>\n",
            "args:(MaxRetryError(\"HTTPConnectionPool(host='futaba-p.co.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20e48306d8>: Failed to establish a new connection: [Errno -2] Name or service not known',))\",),)\n",
            "e自身:HTTPConnectionPool(host='futaba-p.co.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20e48306d8>: Failed to establish a new connection: [Errno -2] Name or service not known',))\n",
            "=== エラー内容 完 ===\n",
            "349 pass!\n",
            "350\n",
            "351\n",
            "352\n",
            "353\n",
            "354\n",
            "355\n",
            "356\n",
            "357\n",
            "358\n",
            "359\n",
            "360\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectionError'>\n",
            "args:(MaxRetryError(\"HTTPConnectionPool(host='giga-mart.co.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20e50e45f8>: Failed to establish a new connection: [Errno -2] Name or service not known',))\",),)\n",
            "e自身:HTTPConnectionPool(host='giga-mart.co.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20e50e45f8>: Failed to establish a new connection: [Errno -2] Name or service not known',))\n",
            "=== エラー内容 完 ===\n",
            "361 pass!\n",
            "362\n",
            "363\n",
            "364\n",
            "365\n",
            "366\n",
            "367\n",
            "368\n",
            "369\n",
            "370\n",
            "371\n",
            "372\n",
            "373\n",
            "374\n",
            "375\n",
            "376\n",
            "377\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectionError'>\n",
            "args:(ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',)),)\n",
            "e自身:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))\n",
            "=== エラー内容 完 ===\n",
            "378 pass!\n",
            "379\n",
            "380\n",
            "381\n",
            "382\n",
            "383\n",
            "384\n",
            "385\n",
            "386\n",
            "387\n",
            "388\n",
            "389\n",
            "390\n",
            "391\n",
            "392\n",
            "393\n",
            "394\n",
            "395\n",
            "396\n",
            "397\n",
            "398\n",
            "399\n",
            "400\n",
            "401\n",
            "402\n",
            "403\n",
            "404\n",
            "405\n",
            "406\n",
            "407\n",
            "408\n",
            "409\n",
            "410\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectionError'>\n",
            "args:(MaxRetryError(\"HTTPConnectionPool(host='hikari-lunchgroup.co.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20e56dc2b0>: Failed to establish a new connection: [Errno -2] Name or service not known',))\",),)\n",
            "e自身:HTTPConnectionPool(host='hikari-lunchgroup.co.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20e56dc2b0>: Failed to establish a new connection: [Errno -2] Name or service not known',))\n",
            "=== エラー内容 完 ===\n",
            "411 pass!\n",
            "412\n",
            "413\n",
            "414\n",
            "415\n",
            "416\n",
            "417\n",
            "418\n",
            "419\n",
            "420\n",
            "421\n",
            "422\n",
            "423\n",
            "424\n",
            "425\n",
            "426\n",
            "427\n",
            "428\n",
            "429\n",
            "430\n",
            "431\n",
            "432\n",
            "433\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectionError'>\n",
            "args:(MaxRetryError(\"HTTPConnectionPool(host='homepage3.nifty.com', port=80): Max retries exceeded with url: /ogi-stage-arts/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20e55659e8>: Failed to establish a new connection: [Errno -2] Name or service not known',))\",),)\n",
            "e自身:HTTPConnectionPool(host='homepage3.nifty.com', port=80): Max retries exceeded with url: /ogi-stage-arts/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20e55659e8>: Failed to establish a new connection: [Errno -2] Name or service not known',))\n",
            "=== エラー内容 完 ===\n",
            "434 pass!\n",
            "435\n",
            "436\n",
            "437\n",
            "438\n",
            "439\n",
            "440\n",
            "441\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectionError'>\n",
            "args:(MaxRetryError(\"HTTPConnectionPool(host='hotta-seishindo.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20e52613c8>: Failed to establish a new connection: [Errno -2] Name or service not known',))\",),)\n",
            "e自身:HTTPConnectionPool(host='hotta-seishindo.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20e52613c8>: Failed to establish a new connection: [Errno -2] Name or service not known',))\n",
            "=== エラー内容 完 ===\n",
            "442 pass!\n",
            "443\n",
            "444\n",
            "445\n",
            "446\n",
            "447\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectionError'>\n",
            "args:(MaxRetryError(\"HTTPConnectionPool(host='hugo-career.co.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20e4f1f128>: Failed to establish a new connection: [Errno -2] Name or service not known',))\",),)\n",
            "e自身:HTTPConnectionPool(host='hugo-career.co.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20e4f1f128>: Failed to establish a new connection: [Errno -2] Name or service not known',))\n",
            "=== エラー内容 完 ===\n",
            "448 pass!\n",
            "449\n",
            "450\n",
            "451\n",
            "452\n",
            "453\n",
            "454\n",
            "455\n",
            "456\n",
            "457\n",
            "458\n",
            "459\n",
            "460\n",
            "461\n",
            "462\n",
            "463\n",
            "464\n",
            "465\n",
            "466\n",
            "467\n",
            "468\n",
            "469\n",
            "470\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectTimeout'>\n",
            "args:(MaxRetryError(\"HTTPConnectionPool(host='impex-ipoint.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f20e55b3320>, 'Connection to impex-ipoint.com timed out. (connect timeout=10)'))\",),)\n",
            "e自身:HTTPConnectionPool(host='impex-ipoint.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f20e55b3320>, 'Connection to impex-ipoint.com timed out. (connect timeout=10)'))\n",
            "=== エラー内容 完 ===\n",
            "471 pass!\n",
            "472\n",
            "473\n",
            "474\n",
            "475\n",
            "476\n",
            "477\n",
            "478\n",
            "479\n",
            "480\n",
            "481\n",
            "482\n",
            "483\n",
            "484\n",
            "485\n",
            "486\n",
            "487\n",
            "488\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.SSLError'>\n",
            "args:(MaxRetryError(\"HTTPSConnectionPool(host='ishida-watch.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))\",),)\n",
            "e自身:HTTPSConnectionPool(host='ishida-watch.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))\n",
            "=== エラー内容 完 ===\n",
            "489 pass!\n",
            "490\n",
            "491\n",
            "492\n",
            "493\n",
            "494\n",
            "495\n",
            "496\n",
            "497\n",
            "498\n",
            "499\n",
            "500\n",
            "501\n",
            "502\n",
            "503\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectionError'>\n",
            "args:(MaxRetryError(\"HTTPConnectionPool(host='ixon.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20e6ad42e8>: Failed to establish a new connection: [Errno -2] Name or service not known',))\",),)\n",
            "e自身:HTTPConnectionPool(host='ixon.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20e6ad42e8>: Failed to establish a new connection: [Errno -2] Name or service not known',))\n",
            "=== エラー内容 完 ===\n",
            "504 pass!\n",
            "505\n",
            "506\n",
            "507\n",
            "508\n",
            "509\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectionError'>\n",
            "args:(ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')),)\n",
            "e自身:('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))\n",
            "=== エラー内容 完 ===\n",
            "510 pass!\n",
            "511\n",
            "512\n",
            "513\n",
            "514\n",
            "515\n",
            "516\n",
            "517\n",
            "518\n",
            "519\n",
            "520\n",
            "521\n",
            "522\n",
            "523\n",
            "524\n",
            "525\n",
            "526\n",
            "527\n",
            "528\n",
            "529\n",
            "530\n",
            "531\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectionError'>\n",
            "args:(MaxRetryError(\"HTTPConnectionPool(host='josaidk.co.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20e48990f0>: Failed to establish a new connection: [Errno -2] Name or service not known',))\",),)\n",
            "e自身:HTTPConnectionPool(host='josaidk.co.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20e48990f0>: Failed to establish a new connection: [Errno -2] Name or service not known',))\n",
            "=== エラー内容 完 ===\n",
            "532 pass!\n",
            "533\n",
            "534\n",
            "535\n",
            "536\n",
            "537\n",
            "538\n",
            "539\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectionError'>\n",
            "args:(MaxRetryError(\"HTTPConnectionPool(host='jp.hondatrading.com', port=80): Max retries exceeded with url: /jp/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20e54ab390>: Failed to establish a new connection: [Errno -2] Name or service not known',))\",),)\n",
            "e自身:HTTPConnectionPool(host='jp.hondatrading.com', port=80): Max retries exceeded with url: /jp/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20e54ab390>: Failed to establish a new connection: [Errno -2] Name or service not known',))\n",
            "=== エラー内容 完 ===\n",
            "540 pass!\n",
            "541\n",
            "542\n",
            "543\n",
            "544\n",
            "545\n",
            "546\n",
            "547\n",
            "548\n",
            "549\n",
            "550\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectionError'>\n",
            "args:(MaxRetryError(\"HTTPConnectionPool(host='j-shiyaku.ehost.jp', port=80): Max retries exceeded with url: /cgi/shiyaku/pubview.asp?id=taisei (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20e5771940>: Failed to establish a new connection: [Errno -2] Name or service not known',))\",),)\n",
            "e自身:HTTPConnectionPool(host='j-shiyaku.ehost.jp', port=80): Max retries exceeded with url: /cgi/shiyaku/pubview.asp?id=taisei (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20e5771940>: Failed to establish a new connection: [Errno -2] Name or service not known',))\n",
            "=== エラー内容 完 ===\n",
            "551 pass!\n",
            "552\n",
            "553\n",
            "554\n",
            "555\n",
            "556\n",
            "557\n",
            "558\n",
            "559\n",
            "560\n",
            "561\n",
            "562\n",
            "563\n",
            "564\n",
            "565\n",
            "566\n",
            "567\n",
            "568\n",
            "569\n",
            "570\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectionError'>\n",
            "args:(MaxRetryError(\"HTTPConnectionPool(host='kamakuraham.tokyo', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20e4f9d828>: Failed to establish a new connection: [Errno -2] Name or service not known',))\",),)\n",
            "e自身:HTTPConnectionPool(host='kamakuraham.tokyo', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20e4f9d828>: Failed to establish a new connection: [Errno -2] Name or service not known',))\n",
            "=== エラー内容 完 ===\n",
            "571 pass!\n",
            "572\n",
            "573\n",
            "574\n",
            "575\n",
            "576\n",
            "577\n",
            "578\n",
            "579\n",
            "580\n",
            "581\n",
            "582\n",
            "583\n",
            "584\n",
            "585\n",
            "586\n",
            "587\n",
            "588\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectTimeout'>\n",
            "args:(MaxRetryError(\"HTTPConnectionPool(host='kawaicosme.co.jp', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f20e5764748>, 'Connection to kawaicosme.co.jp timed out. (connect timeout=10)'))\",),)\n",
            "e自身:HTTPConnectionPool(host='kawaicosme.co.jp', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f20e5764748>, 'Connection to kawaicosme.co.jp timed out. (connect timeout=10)'))\n",
            "=== エラー内容 完 ===\n",
            "589 pass!\n",
            "590\n",
            "591\n",
            "592\n",
            "593\n",
            "594\n",
            "595\n",
            "596\n",
            "597\n",
            "598\n",
            "599\n",
            "600\n",
            "601\n",
            "602\n",
            "603\n",
            "604\n",
            "605\n",
            "606\n",
            "607\n",
            "608\n",
            "609\n",
            "610\n",
            "611\n",
            "612\n",
            "613\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectionError'>\n",
            "args:(MaxRetryError(\"HTTPConnectionPool(host='kisaki-con.co.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20e4f11908>: Failed to establish a new connection: [Errno -2] Name or service not known',))\",),)\n",
            "e自身:HTTPConnectionPool(host='kisaki-con.co.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20e4f11908>: Failed to establish a new connection: [Errno -2] Name or service not known',))\n",
            "=== エラー内容 完 ===\n",
            "614 pass!\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectionError'>\n",
            "args:(MaxRetryError(\"HTTPConnectionPool(host='kissbee-shop.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20e50e8ef0>: Failed to establish a new connection: [Errno -2] Name or service not known',))\",),)\n",
            "e自身:HTTPConnectionPool(host='kissbee-shop.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20e50e8ef0>: Failed to establish a new connection: [Errno -2] Name or service not known',))\n",
            "=== エラー内容 完 ===\n",
            "615 pass!\n",
            "616\n",
            "617\n",
            "618\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectionError'>\n",
            "args:(MaxRetryError(\"HTTPConnectionPool(host='kk-fff.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20e4ee8080>: Failed to establish a new connection: [Errno -2] Name or service not known',))\",),)\n",
            "e自身:HTTPConnectionPool(host='kk-fff.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20e4ee8080>: Failed to establish a new connection: [Errno -2] Name or service not known',))\n",
            "=== エラー内容 完 ===\n",
            "619 pass!\n",
            "620\n",
            "621\n",
            "622\n",
            "623\n",
            "624\n",
            "625\n",
            "626\n",
            "627\n",
            "628\n",
            "629\n",
            "630\n",
            "631\n",
            "632\n",
            "633\n",
            "634\n",
            "635\n",
            "636\n",
            "637\n",
            "638\n",
            "639\n",
            "640\n",
            "641\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectionError'>\n",
            "args:(MaxRetryError(\"HTTPConnectionPool(host='ktnj.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20e4f76898>: Failed to establish a new connection: [Errno -2] Name or service not known',))\",),)\n",
            "e自身:HTTPConnectionPool(host='ktnj.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20e4f76898>: Failed to establish a new connection: [Errno -2] Name or service not known',))\n",
            "=== エラー内容 完 ===\n",
            "642 pass!\n",
            "643\n",
            "644\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectionError'>\n",
            "args:(MaxRetryError(\"HTTPConnectionPool(host='k-yakuzen.net', port=80): Max retries exceeded with url: /shop/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20e57b19b0>: Failed to establish a new connection: [Errno -2] Name or service not known',))\",),)\n",
            "e自身:HTTPConnectionPool(host='k-yakuzen.net', port=80): Max retries exceeded with url: /shop/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20e57b19b0>: Failed to establish a new connection: [Errno -2] Name or service not known',))\n",
            "=== エラー内容 完 ===\n",
            "645 pass!\n",
            "646\n",
            "647\n",
            "648\n",
            "649\n",
            "650\n",
            "651\n",
            "652\n",
            "653\n",
            "654\n",
            "655\n",
            "656\n",
            "657\n",
            "658\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ReadTimeout'>\n",
            "args:(ReadTimeoutError(\"HTTPConnectionPool(host='largu.co.jp', port=80): Read timed out. (read timeout=10)\",),)\n",
            "e自身:HTTPConnectionPool(host='largu.co.jp', port=80): Read timed out. (read timeout=10)\n",
            "=== エラー内容 完 ===\n",
            "659 pass!\n",
            "660\n",
            "661\n",
            "662\n",
            "663\n",
            "664\n",
            "665\n",
            "666\n",
            "667\n",
            "668\n",
            "669\n",
            "670\n",
            "671\n",
            "672\n",
            "673\n",
            "674\n",
            "675\n",
            "676\n",
            "677\n",
            "678\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectionError'>\n",
            "args:(MaxRetryError(\"HTTPConnectionPool(host='livesenseconnect.co.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20e4e57e48>: Failed to establish a new connection: [Errno -5] No address associated with hostname',))\",),)\n",
            "e自身:HTTPConnectionPool(host='livesenseconnect.co.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20e4e57e48>: Failed to establish a new connection: [Errno -5] No address associated with hostname',))\n",
            "=== エラー内容 完 ===\n",
            "679 pass!\n",
            "680\n",
            "681\n",
            "682\n",
            "683\n",
            "684\n",
            "685\n",
            "686\n",
            "687\n",
            "688\n",
            "689\n",
            "690\n",
            "691\n",
            "692\n",
            "693\n",
            "694\n",
            "695\n",
            "696\n",
            "697\n",
            "698\n",
            "699\n",
            "700\n",
            "701\n",
            "702\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectionError'>\n",
            "args:(MaxRetryError(\"HTTPConnectionPool(host='marucos.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20e5273710>: Failed to establish a new connection: [Errno -2] Name or service not known',))\",),)\n",
            "e自身:HTTPConnectionPool(host='marucos.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20e5273710>: Failed to establish a new connection: [Errno -2] Name or service not known',))\n",
            "=== エラー内容 完 ===\n",
            "703 pass!\n",
            "704\n",
            "705\n",
            "706\n",
            "707\n",
            "708\n",
            "709\n",
            "710\n",
            "711\n",
            "712\n",
            "713\n",
            "714\n",
            "715\n",
            "716\n",
            "717\n",
            "718\n",
            "719\n",
            "720\n",
            "721\n",
            "722\n",
            "723\n",
            "724\n",
            "725\n",
            "726\n",
            "727\n",
            "728\n",
            "729\n",
            "730\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectionError'>\n",
            "args:(MaxRetryError(\"HTTPConnectionPool(host='medicalpine.com', port=80): Max retries exceeded with url: /en/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20e5175320>: Failed to establish a new connection: [Errno -2] Name or service not known',))\",),)\n",
            "e自身:HTTPConnectionPool(host='medicalpine.com', port=80): Max retries exceeded with url: /en/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20e5175320>: Failed to establish a new connection: [Errno -2] Name or service not known',))\n",
            "=== エラー内容 完 ===\n",
            "731 pass!\n",
            "732\n",
            "733\n",
            "734\n",
            "735\n",
            "736\n",
            "737\n",
            "738\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectionError'>\n",
            "args:(MaxRetryError(\"HTTPConnectionPool(host='meisei-shop.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20e4671438>: Failed to establish a new connection: [Errno -2] Name or service not known',))\",),)\n",
            "e自身:HTTPConnectionPool(host='meisei-shop.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20e4671438>: Failed to establish a new connection: [Errno -2] Name or service not known',))\n",
            "=== エラー内容 完 ===\n",
            "739 pass!\n",
            "740\n",
            "741\n",
            "742\n",
            "743\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ReadTimeout'>\n",
            "args:(ReadTimeoutError(\"HTTPConnectionPool(host='melco-y.co.jp', port=80): Read timed out. (read timeout=10)\",),)\n",
            "e自身:HTTPConnectionPool(host='melco-y.co.jp', port=80): Read timed out. (read timeout=10)\n",
            "=== エラー内容 完 ===\n",
            "744 pass!\n",
            "745\n",
            "746\n",
            "747\n",
            "748\n",
            "749\n",
            "750\n",
            "751\n",
            "752\n",
            "753\n",
            "754\n",
            "755\n",
            "756\n",
            "757\n",
            "758\n",
            "759\n",
            "760\n",
            "761\n",
            "762\n",
            "763\n",
            "764\n",
            "765\n",
            "766\n",
            "767\n",
            "768\n",
            "769\n",
            "770\n",
            "771\n",
            "772\n",
            "773\n",
            "774\n",
            "775\n",
            "776\n",
            "777\n",
            "778\n",
            "779\n",
            "780\n",
            "781\n",
            "782\n",
            "783\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectionError'>\n",
            "args:(MaxRetryError(\"HTTPConnectionPool(host='ms-crystal.co.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20e5789e10>: Failed to establish a new connection: [Errno -2] Name or service not known',))\",),)\n",
            "e自身:HTTPConnectionPool(host='ms-crystal.co.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20e5789e10>: Failed to establish a new connection: [Errno -2] Name or service not known',))\n",
            "=== エラー内容 完 ===\n",
            "784 pass!\n",
            "785\n",
            "786\n",
            "787\n",
            "788\n",
            "789\n",
            "790\n",
            "791\n",
            "792\n",
            "793\n",
            "794\n",
            "795\n",
            "796\n",
            "797\n",
            "798\n",
            "799\n",
            "800\n",
            "801\n",
            "802\n",
            "803\n",
            "804\n",
            "805\n",
            "806\n",
            "807\n",
            "808\n",
            "809\n",
            "810\n",
            "811\n",
            "812\n",
            "813\n",
            "814\n",
            "815\n",
            "816\n",
            "817\n",
            "818\n",
            "819\n",
            "820\n",
            "821\n",
            "822\n",
            "823\n",
            "824\n",
            "825\n",
            "826\n",
            "827\n",
            "828\n",
            "829\n",
            "830\n",
            "831\n",
            "832\n",
            "833\n",
            "834\n",
            "835\n",
            "836\n",
            "837\n",
            "838\n",
            "839\n",
            "840\n",
            "841\n",
            "842\n",
            "843\n",
            "844\n",
            "845\n",
            "846\n",
            "847\n",
            "848\n",
            "849\n",
            "850\n",
            "851\n",
            "852\n",
            "853\n",
            "854\n",
            "855\n",
            "856\n",
            "857\n",
            "858\n",
            "859\n",
            "860\n",
            "861\n",
            "862\n",
            "863\n",
            "864\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.SSLError'>\n",
            "args:(MaxRetryError(\"HTTPSConnectionPool(host='nmtecs.jp', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))\",),)\n",
            "e自身:HTTPSConnectionPool(host='nmtecs.jp', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))\n",
            "=== エラー内容 完 ===\n",
            "865 pass!\n",
            "866\n",
            "867\n",
            "868\n",
            "869\n",
            "870\n",
            "871\n",
            "872\n",
            "873\n",
            "874\n",
            "875\n",
            "876\n",
            "877\n",
            "878\n",
            "879\n",
            "880\n",
            "881\n",
            "882\n",
            "883\n",
            "884\n",
            "885\n",
            "886\n",
            "887\n",
            "888\n",
            "889\n",
            "890\n",
            "891\n",
            "892\n",
            "893\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectTimeout'>\n",
            "args:(MaxRetryError(\"HTTPConnectionPool(host='old.struers.dk', port=80): Max retries exceeded with url: /default.asp?top_id=0&main_id=0&sub_id=0&doc_id=805&admin_language=5 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f20e57b4710>, 'Connection to old.struers.dk timed out. (connect timeout=10)'))\",),)\n",
            "e自身:HTTPConnectionPool(host='old.struers.dk', port=80): Max retries exceeded with url: /default.asp?top_id=0&main_id=0&sub_id=0&doc_id=805&admin_language=5 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f20e57b4710>, 'Connection to old.struers.dk timed out. (connect timeout=10)'))\n",
            "=== エラー内容 完 ===\n",
            "894 pass!\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.InvalidURL'>\n",
            "args:(LocationValueError('No host specified.',),)\n",
            "e自身:No host specified.\n",
            "=== エラー内容 完 ===\n",
            "895 pass!\n",
            "896\n",
            "897\n",
            "898\n",
            "899\n",
            "900\n",
            "901\n",
            "902\n",
            "903\n",
            "904\n",
            "905\n",
            "906\n",
            "907\n",
            "908\n",
            "909\n",
            "910\n",
            "911\n",
            "912\n",
            "913\n",
            "914\n",
            "915\n",
            "916\n",
            "917\n",
            "918\n",
            "919\n",
            "920\n",
            "921\n",
            "922\n",
            "923\n",
            "924\n",
            "925\n",
            "926\n",
            "927\n",
            "928\n",
            "929\n",
            "930\n",
            "931\n",
            "932\n",
            "933\n",
            "934\n",
            "935\n",
            "936\n",
            "937\n",
            "938\n",
            "939\n",
            "940\n",
            "941\n",
            "942\n",
            "943\n",
            "944\n",
            "945\n",
            "946\n",
            "947\n",
            "948\n",
            "949\n",
            "950\n",
            "951\n",
            "952\n",
            "953\n",
            "954\n",
            "955\n",
            "956\n",
            "957\n",
            "958\n",
            "959\n",
            "960\n",
            "961\n",
            "962\n",
            "963\n",
            "964\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectionError'>\n",
            "args:(MaxRetryError(\"HTTPConnectionPool(host='riecco.co.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20e48ad2b0>: Failed to establish a new connection: [Errno -2] Name or service not known',))\",),)\n",
            "e自身:HTTPConnectionPool(host='riecco.co.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20e48ad2b0>: Failed to establish a new connection: [Errno -2] Name or service not known',))\n",
            "=== エラー内容 完 ===\n",
            "965 pass!\n",
            "966\n",
            "967\n",
            "968\n",
            "969\n",
            "970\n",
            "971\n",
            "972\n",
            "973\n",
            "974\n",
            "975\n",
            "976\n",
            "977\n",
            "978\n",
            "979\n",
            "980\n",
            "981\n",
            "982\n",
            "983\n",
            "984\n",
            "985\n",
            "986\n",
            "987\n",
            "988\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectionError'>\n",
            "args:(MaxRetryError(\"HTTPConnectionPool(host='sandvik.info', port=80): Max retries exceeded with url: /ja-jp/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20e5155f60>: Failed to establish a new connection: [Errno -2] Name or service not known',))\",),)\n",
            "e自身:HTTPConnectionPool(host='sandvik.info', port=80): Max retries exceeded with url: /ja-jp/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20e5155f60>: Failed to establish a new connection: [Errno -2] Name or service not known',))\n",
            "=== エラー内容 完 ===\n",
            "989 pass!\n",
            "990\n",
            "991\n",
            "992\n",
            "993\n",
            "994\n",
            "995\n",
            "996\n",
            "997\n",
            "998\n",
            "999\n",
            "1000\n",
            "1001\n",
            "1002\n",
            "1003\n",
            "1004\n",
            "1005\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectionError'>\n",
            "args:(MaxRetryError(\"HTTPConnectionPool(host='sc-erg.co.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20e55e76a0>: Failed to establish a new connection: [Errno -2] Name or service not known',))\",),)\n",
            "e自身:HTTPConnectionPool(host='sc-erg.co.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20e55e76a0>: Failed to establish a new connection: [Errno -2] Name or service not known',))\n",
            "=== エラー内容 完 ===\n",
            "1006 pass!\n",
            "1007\n",
            "1008\n",
            "1009\n",
            "1010\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectTimeout'>\n",
            "args:(MaxRetryError(\"HTTPConnectionPool(host='seidai-tokyo.co.jp', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f20e4ead550>, 'Connection to seidai-tokyo.co.jp timed out. (connect timeout=10)'))\",),)\n",
            "e自身:HTTPConnectionPool(host='seidai-tokyo.co.jp', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f20e4ead550>, 'Connection to seidai-tokyo.co.jp timed out. (connect timeout=10)'))\n",
            "=== エラー内容 完 ===\n",
            "1011 pass!\n",
            "1012\n",
            "1013\n",
            "1014\n",
            "1015\n",
            "1016\n",
            "1017\n",
            "1018\n",
            "1019\n",
            "1020\n",
            "1021\n",
            "1022\n",
            "1023\n",
            "1024\n",
            "1025\n",
            "1026\n",
            "1027\n",
            "1028\n",
            "1029\n",
            "1030\n",
            "1031\n",
            "1032\n",
            "1033\n",
            "1034\n",
            "1035\n",
            "1036\n",
            "1037\n",
            "1038\n",
            "1039\n",
            "1040\n",
            "1041\n",
            "1042\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectTimeout'>\n",
            "args:(MaxRetryError(\"HTTPConnectionPool(host='shoeishokai.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f20e4f36828>, 'Connection to shoeishokai.com timed out. (connect timeout=10)'))\",),)\n",
            "e自身:HTTPConnectionPool(host='shoeishokai.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f20e4f36828>, 'Connection to shoeishokai.com timed out. (connect timeout=10)'))\n",
            "=== エラー内容 完 ===\n",
            "1043 pass!\n",
            "1044\n",
            "1045\n",
            "1046\n",
            "1047\n",
            "1048\n",
            "1049\n",
            "1050\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectionError'>\n",
            "args:(MaxRetryError(\"HTTPConnectionPool(host='showamuranouen.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20e4d9c0f0>: Failed to establish a new connection: [Errno -2] Name or service not known',))\",),)\n",
            "e自身:HTTPConnectionPool(host='showamuranouen.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20e4d9c0f0>: Failed to establish a new connection: [Errno -2] Name or service not known',))\n",
            "=== エラー内容 完 ===\n",
            "1051 pass!\n",
            "1052\n",
            "1053\n",
            "1054\n",
            "1055\n",
            "1056\n",
            "1057\n",
            "1058\n",
            "1059\n",
            "1060\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.SSLError'>\n",
            "args:(MaxRetryError('HTTPSConnectionPool(host=\\'sj-minamitokyo.jp\\', port=443): Max retries exceeded with url: / (Caused by SSLError(CertificateError(\"hostname \\'sj-minamitokyo.jp\\' doesn\\'t match either of \\'*.xserver.jp\\', \\'xserver.jp\\'\",),))',),)\n",
            "e自身:HTTPSConnectionPool(host='sj-minamitokyo.jp', port=443): Max retries exceeded with url: / (Caused by SSLError(CertificateError(\"hostname 'sj-minamitokyo.jp' doesn't match either of '*.xserver.jp', 'xserver.jp'\",),))\n",
            "=== エラー内容 完 ===\n",
            "1061 pass!\n",
            "1062\n",
            "1063\n",
            "1064\n"
          ],
          "name": "stdout"
        }
      ]
    }
  ]
}