{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "name": "他社使用ツール調査.ipynb",
      "provenance": [],
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/kenkono5/analytics_competitor_tools/blob/master/%E4%BB%96%E7%A4%BE%E4%BD%BF%E7%94%A8%E3%83%84%E3%83%BC%E3%83%AB%E8%AA%BF%E6%9F%BB.ipynb\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "7wEtWN1QHLAN",
        "colab_type": "code",
        "colab": {
          "resources": {
            "http://localhost:8080/nbextensions/google.colab/files.js": {
              "data": "Ly8gQ29weXJpZ2h0IDIwMTcgR29vZ2xlIExMQwovLwovLyBMaWNlbnNlZCB1bmRlciB0aGUgQXBhY2hlIExpY2Vuc2UsIFZlcnNpb24gMi4wICh0aGUgIkxpY2Vuc2UiKTsKLy8geW91IG1heSBub3QgdXNlIHRoaXMgZmlsZSBleGNlcHQgaW4gY29tcGxpYW5jZSB3aXRoIHRoZSBMaWNlbnNlLgovLyBZb3UgbWF5IG9idGFpbiBhIGNvcHkgb2YgdGhlIExpY2Vuc2UgYXQKLy8KLy8gICAgICBodHRwOi8vd3d3LmFwYWNoZS5vcmcvbGljZW5zZXMvTElDRU5TRS0yLjAKLy8KLy8gVW5sZXNzIHJlcXVpcmVkIGJ5IGFwcGxpY2FibGUgbGF3IG9yIGFncmVlZCB0byBpbiB3cml0aW5nLCBzb2Z0d2FyZQovLyBkaXN0cmlidXRlZCB1bmRlciB0aGUgTGljZW5zZSBpcyBkaXN0cmlidXRlZCBvbiBhbiAiQVMgSVMiIEJBU0lTLAovLyBXSVRIT1VUIFdBUlJBTlRJRVMgT1IgQ09ORElUSU9OUyBPRiBBTlkgS0lORCwgZWl0aGVyIGV4cHJlc3Mgb3IgaW1wbGllZC4KLy8gU2VlIHRoZSBMaWNlbnNlIGZvciB0aGUgc3BlY2lmaWMgbGFuZ3VhZ2UgZ292ZXJuaW5nIHBlcm1pc3Npb25zIGFuZAovLyBsaW1pdGF0aW9ucyB1bmRlciB0aGUgTGljZW5zZS4KCi8qKgogKiBAZmlsZW92ZXJ2aWV3IEhlbHBlcnMgZm9yIGdvb2dsZS5jb2xhYiBQeXRob24gbW9kdWxlLgogKi8KKGZ1bmN0aW9uKHNjb3BlKSB7CmZ1bmN0aW9uIHNwYW4odGV4dCwgc3R5bGVBdHRyaWJ1dGVzID0ge30pIHsKICBjb25zdCBlbGVtZW50ID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnc3BhbicpOwogIGVsZW1lbnQudGV4dENvbnRlbnQgPSB0ZXh0OwogIGZvciAoY29uc3Qga2V5IG9mIE9iamVjdC5rZXlzKHN0eWxlQXR0cmlidXRlcykpIHsKICAgIGVsZW1lbnQuc3R5bGVba2V5XSA9IHN0eWxlQXR0cmlidXRlc1trZXldOwogIH0KICByZXR1cm4gZWxlbWVudDsKfQoKLy8gTWF4IG51bWJlciBvZiBieXRlcyB3aGljaCB3aWxsIGJlIHVwbG9hZGVkIGF0IGEgdGltZS4KY29uc3QgTUFYX1BBWUxPQURfU0laRSA9IDEwMCAqIDEwMjQ7CgpmdW5jdGlvbiBfdXBsb2FkRmlsZXMoaW5wdXRJZCwgb3V0cHV0SWQpIHsKICBjb25zdCBzdGVwcyA9IHVwbG9hZEZpbGVzU3RlcChpbnB1dElkLCBvdXRwdXRJZCk7CiAgY29uc3Qgb3V0cHV0RWxlbWVudCA9IGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKG91dHB1dElkKTsKICAvLyBDYWNoZSBzdGVwcyBvbiB0aGUgb3V0cHV0RWxlbWVudCB0byBtYWtlIGl0IGF2YWlsYWJsZSBmb3IgdGhlIG5leHQgY2FsbAogIC8vIHRvIHVwbG9hZEZpbGVzQ29udGludWUgZnJvbSBQeXRob24uCiAgb3V0cHV0RWxlbWVudC5zdGVwcyA9IHN0ZXBzOwoKICByZXR1cm4gX3VwbG9hZEZpbGVzQ29udGludWUob3V0cHV0SWQpOwp9CgovLyBUaGlzIGlzIHJvdWdobHkgYW4gYXN5bmMgZ2VuZXJhdG9yIChub3Qgc3VwcG9ydGVkIGluIHRoZSBicm93c2VyIHlldCksCi8vIHdoZXJlIHRoZXJlIGFyZSBtdWx0aXBsZSBhc3luY2hyb25vdXMgc3RlcHMgYW5kIHRoZSBQeXRob24gc2lkZSBpcyBnb2luZwovLyB0byBwb2xsIGZvciBjb21wbGV0aW9uIG9mIGVhY2ggc3RlcC4KLy8gVGhpcyB1c2VzIGEgUHJvbWlzZSB0byBibG9jayB0aGUgcHl0aG9uIHNpZGUgb24gY29tcGxldGlvbiBvZiBlYWNoIHN0ZXAsCi8vIHRoZW4gcGFzc2VzIHRoZSByZXN1bHQgb2YgdGhlIHByZXZpb3VzIHN0ZXAgYXMgdGhlIGlucHV0IHRvIHRoZSBuZXh0IHN0ZXAuCmZ1bmN0aW9uIF91cGxvYWRGaWxlc0NvbnRpbnVlKG91dHB1dElkKSB7CiAgY29uc3Qgb3V0cHV0RWxlbWVudCA9IGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKG91dHB1dElkKTsKICBjb25zdCBzdGVwcyA9IG91dHB1dEVsZW1lbnQuc3RlcHM7CgogIGNvbnN0IG5leHQgPSBzdGVwcy5uZXh0KG91dHB1dEVsZW1lbnQubGFzdFByb21pc2VWYWx1ZSk7CiAgcmV0dXJuIFByb21pc2UucmVzb2x2ZShuZXh0LnZhbHVlLnByb21pc2UpLnRoZW4oKHZhbHVlKSA9PiB7CiAgICAvLyBDYWNoZSB0aGUgbGFzdCBwcm9taXNlIHZhbHVlIHRvIG1ha2UgaXQgYXZhaWxhYmxlIHRvIHRoZSBuZXh0CiAgICAvLyBzdGVwIG9mIHRoZSBnZW5lcmF0b3IuCiAgICBvdXRwdXRFbGVtZW50Lmxhc3RQcm9taXNlVmFsdWUgPSB2YWx1ZTsKICAgIHJldHVybiBuZXh0LnZhbHVlLnJlc3BvbnNlOwogIH0pOwp9CgovKioKICogR2VuZXJhdG9yIGZ1bmN0aW9uIHdoaWNoIGlzIGNhbGxlZCBiZXR3ZWVuIGVhY2ggYXN5bmMgc3RlcCBvZiB0aGUgdXBsb2FkCiAqIHByb2Nlc3MuCiAqIEBwYXJhbSB7c3RyaW5nfSBpbnB1dElkIEVsZW1lbnQgSUQgb2YgdGhlIGlucHV0IGZpbGUgcGlja2VyIGVsZW1lbnQuCiAqIEBwYXJhbSB7c3RyaW5nfSBvdXRwdXRJZCBFbGVtZW50IElEIG9mIHRoZSBvdXRwdXQgZGlzcGxheS4KICogQHJldHVybiB7IUl0ZXJhYmxlPCFPYmplY3Q+fSBJdGVyYWJsZSBvZiBuZXh0IHN0ZXBzLgogKi8KZnVuY3Rpb24qIHVwbG9hZEZpbGVzU3RlcChpbnB1dElkLCBvdXRwdXRJZCkgewogIGNvbnN0IGlucHV0RWxlbWVudCA9IGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKGlucHV0SWQpOwogIGlucHV0RWxlbWVudC5kaXNhYmxlZCA9IGZhbHNlOwoKICBjb25zdCBvdXRwdXRFbGVtZW50ID0gZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQob3V0cHV0SWQpOwogIG91dHB1dEVsZW1lbnQuaW5uZXJIVE1MID0gJyc7CgogIGNvbnN0IHBpY2tlZFByb21pc2UgPSBuZXcgUHJvbWlzZSgocmVzb2x2ZSkgPT4gewogICAgaW5wdXRFbGVtZW50LmFkZEV2ZW50TGlzdGVuZXIoJ2NoYW5nZScsIChlKSA9PiB7CiAgICAgIHJlc29sdmUoZS50YXJnZXQuZmlsZXMpOwogICAgfSk7CiAgfSk7CgogIGNvbnN0IGNhbmNlbCA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2J1dHRvbicpOwogIGlucHV0RWxlbWVudC5wYXJlbnRFbGVtZW50LmFwcGVuZENoaWxkKGNhbmNlbCk7CiAgY2FuY2VsLnRleHRDb250ZW50ID0gJ0NhbmNlbCB1cGxvYWQnOwogIGNvbnN0IGNhbmNlbFByb21pc2UgPSBuZXcgUHJvbWlzZSgocmVzb2x2ZSkgPT4gewogICAgY2FuY2VsLm9uY2xpY2sgPSAoKSA9PiB7CiAgICAgIHJlc29sdmUobnVsbCk7CiAgICB9OwogIH0pOwoKICAvLyBXYWl0IGZvciB0aGUgdXNlciB0byBwaWNrIHRoZSBmaWxlcy4KICBjb25zdCBmaWxlcyA9IHlpZWxkIHsKICAgIHByb21pc2U6IFByb21pc2UucmFjZShbcGlja2VkUHJvbWlzZSwgY2FuY2VsUHJvbWlzZV0pLAogICAgcmVzcG9uc2U6IHsKICAgICAgYWN0aW9uOiAnc3RhcnRpbmcnLAogICAgfQogIH07CgogIGNhbmNlbC5yZW1vdmUoKTsKCiAgLy8gRGlzYWJsZSB0aGUgaW5wdXQgZWxlbWVudCBzaW5jZSBmdXJ0aGVyIHBpY2tzIGFyZSBub3QgYWxsb3dlZC4KICBpbnB1dEVsZW1lbnQuZGlzYWJsZWQgPSB0cnVlOwoKICBpZiAoIWZpbGVzKSB7CiAgICByZXR1cm4gewogICAgICByZXNwb25zZTogewogICAgICAgIGFjdGlvbjogJ2NvbXBsZXRlJywKICAgICAgfQogICAgfTsKICB9CgogIGZvciAoY29uc3QgZmlsZSBvZiBmaWxlcykgewogICAgY29uc3QgbGkgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdsaScpOwogICAgbGkuYXBwZW5kKHNwYW4oZmlsZS5uYW1lLCB7Zm9udFdlaWdodDogJ2JvbGQnfSkpOwogICAgbGkuYXBwZW5kKHNwYW4oCiAgICAgICAgYCgke2ZpbGUudHlwZSB8fCAnbi9hJ30pIC0gJHtmaWxlLnNpemV9IGJ5dGVzLCBgICsKICAgICAgICBgbGFzdCBtb2RpZmllZDogJHsKICAgICAgICAgICAgZmlsZS5sYXN0TW9kaWZpZWREYXRlID8gZmlsZS5sYXN0TW9kaWZpZWREYXRlLnRvTG9jYWxlRGF0ZVN0cmluZygpIDoKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgJ24vYSd9IC0gYCkpOwogICAgY29uc3QgcGVyY2VudCA9IHNwYW4oJzAlIGRvbmUnKTsKICAgIGxpLmFwcGVuZENoaWxkKHBlcmNlbnQpOwoKICAgIG91dHB1dEVsZW1lbnQuYXBwZW5kQ2hpbGQobGkpOwoKICAgIGNvbnN0IGZpbGVEYXRhUHJvbWlzZSA9IG5ldyBQcm9taXNlKChyZXNvbHZlKSA9PiB7CiAgICAgIGNvbnN0IHJlYWRlciA9IG5ldyBGaWxlUmVhZGVyKCk7CiAgICAgIHJlYWRlci5vbmxvYWQgPSAoZSkgPT4gewogICAgICAgIHJlc29sdmUoZS50YXJnZXQucmVzdWx0KTsKICAgICAgfTsKICAgICAgcmVhZGVyLnJlYWRBc0FycmF5QnVmZmVyKGZpbGUpOwogICAgfSk7CiAgICAvLyBXYWl0IGZvciB0aGUgZGF0YSB0byBiZSByZWFkeS4KICAgIGxldCBmaWxlRGF0YSA9IHlpZWxkIHsKICAgICAgcHJvbWlzZTogZmlsZURhdGFQcm9taXNlLAogICAgICByZXNwb25zZTogewogICAgICAgIGFjdGlvbjogJ2NvbnRpbnVlJywKICAgICAgfQogICAgfTsKCiAgICAvLyBVc2UgYSBjaHVua2VkIHNlbmRpbmcgdG8gYXZvaWQgbWVzc2FnZSBzaXplIGxpbWl0cy4gU2VlIGIvNjIxMTU2NjAuCiAgICBsZXQgcG9zaXRpb24gPSAwOwogICAgd2hpbGUgKHBvc2l0aW9uIDwgZmlsZURhdGEuYnl0ZUxlbmd0aCkgewogICAgICBjb25zdCBsZW5ndGggPSBNYXRoLm1pbihmaWxlRGF0YS5ieXRlTGVuZ3RoIC0gcG9zaXRpb24sIE1BWF9QQVlMT0FEX1NJWkUpOwogICAgICBjb25zdCBjaHVuayA9IG5ldyBVaW50OEFycmF5KGZpbGVEYXRhLCBwb3NpdGlvbiwgbGVuZ3RoKTsKICAgICAgcG9zaXRpb24gKz0gbGVuZ3RoOwoKICAgICAgY29uc3QgYmFzZTY0ID0gYnRvYShTdHJpbmcuZnJvbUNoYXJDb2RlLmFwcGx5KG51bGwsIGNodW5rKSk7CiAgICAgIHlpZWxkIHsKICAgICAgICByZXNwb25zZTogewogICAgICAgICAgYWN0aW9uOiAnYXBwZW5kJywKICAgICAgICAgIGZpbGU6IGZpbGUubmFtZSwKICAgICAgICAgIGRhdGE6IGJhc2U2NCwKICAgICAgICB9LAogICAgICB9OwogICAgICBwZXJjZW50LnRleHRDb250ZW50ID0KICAgICAgICAgIGAke01hdGgucm91bmQoKHBvc2l0aW9uIC8gZmlsZURhdGEuYnl0ZUxlbmd0aCkgKiAxMDApfSUgZG9uZWA7CiAgICB9CiAgfQoKICAvLyBBbGwgZG9uZS4KICB5aWVsZCB7CiAgICByZXNwb25zZTogewogICAgICBhY3Rpb246ICdjb21wbGV0ZScsCiAgICB9CiAgfTsKfQoKc2NvcGUuZ29vZ2xlID0gc2NvcGUuZ29vZ2xlIHx8IHt9OwpzY29wZS5nb29nbGUuY29sYWIgPSBzY29wZS5nb29nbGUuY29sYWIgfHwge307CnNjb3BlLmdvb2dsZS5jb2xhYi5fZmlsZXMgPSB7CiAgX3VwbG9hZEZpbGVzLAogIF91cGxvYWRGaWxlc0NvbnRpbnVlLAp9Owp9KShzZWxmKTsK",
              "ok": true,
              "headers": [
                [
                  "content-type",
                  "application/javascript"
                ]
              ],
              "status": 200,
              "status_text": ""
            }
          },
          "base_uri": "https://localhost:8080/",
          "height": 1000
        },
        "outputId": "60de64fd-9f35-4cff-e0c0-621c1c7f78e4"
      },
      "source": [
        "import requests\n",
        "from bs4 import BeautifulSoup as bs\n",
        "from time import sleep\n",
        "\n",
        "from google.colab import files\n",
        "uploaded = files.upload()\n",
        "\n",
        "import pandas as pd\n",
        "\n",
        "# df = pandas.read_excel('test.xlsx', sheet_name=0)\n",
        "# df.to_csv('test.csv', index=False)\n",
        "\n",
        "df= pd.read_csv('./②FUMA_東京_小売全般_マスターデータ.csv', encoding=\"utf_8_sig\")\n",
        "df.head()\n",
        "\n",
        "array = df.values\n",
        "company_name_list = []\n",
        "url_list = []\n",
        "\n",
        "pardot_list = []\n",
        "eloqua_list = []\n",
        "marketo_list = []\n",
        "urlNG_list = []\n",
        "num = 1\n",
        "for value in array:\n",
        "  company_name_list.append(value[3])\n",
        "  url_list.append(value[4])\n",
        "\n",
        "for i, j in zip(url_list, company_name_list):\n",
        "  try:\n",
        "    res = requests.get(i, timeout=10)\n",
        "    print(num)\n",
        "    soup = bs(res.text, 'html.parser')\n",
        "    script_tag = soup.find_all('script')\n",
        "    num += 1\n",
        "    for script in script_tag:\n",
        "      if \"pardot\" in script.text:\n",
        "        pardot_list.append(j)\n",
        "\n",
        "      if \"elqQ\" in script.text:\n",
        "        eloqua_list.append(j)\n",
        "\n",
        "      if \"marketo\" in script.text:\n",
        "        marketo_list.append(j)\n",
        "  except Exception as e: \n",
        "    pass\n",
        "    print(\"=== エラー内容 始 ===\")\n",
        "    print(\"type:\" + str(type(e)))\n",
        "    print(\"args:\" + str(e.args))\n",
        "    print(\"e自身:\" + str(e))\n",
        "    print(\"=== エラー内容 完 ===\")\n",
        "    urlNG_list.append(j)\n",
        "    print(num, \"pass!\") \n",
        "    num += 1\n",
        "\n",
        "print(pardot_list)\n",
        "print(eloqua_list)\n",
        "print(marketo_list)\n",
        "print(urlNG_list)\n",
        "\n",
        "use_pardot = []\n",
        "use_eloqua = []\n",
        "use_marketo = []\n",
        "ng_url = []\n",
        "for value in array:\n",
        "  if value[3] in pardot_list:\n",
        "    use_pardot.append(1)\n",
        "  else:\n",
        "    use_pardot.append(0)\n",
        "\n",
        "  if value[3] in eloqua_list:\n",
        "    use_eloqua.append(1)\n",
        "  else:\n",
        "    use_eloqua.append(0)\n",
        "\n",
        "  if value[3] in marketo_list:\n",
        "    use_marketo.append(1)\n",
        "  else:\n",
        "    use_marketo.append(0)\n",
        "\n",
        "  if value[3] in urlNG_list:\n",
        "    ng_url.append(1)\n",
        "  else:\n",
        "    ng_url.append(0)\n",
        "\n",
        "df['pardot'] = use_pardot\n",
        "df['eloqua'] = use_eloqua\n",
        "df['marketo'] = use_marketo\n",
        "df['NGURL'] = ng_url\n",
        "df.to_csv(\"./完了②FUMA_東京_小売全般_マスターデータ.csv\", encoding=\"utf_8_sig\")"
      ],
      "execution_count": null,
      "outputs": [
        {
          "output_type": "display_data",
          "data": {
            "text/html": [
              "\n",
              "     <input type=\"file\" id=\"files-720fcddd-9fc2-4542-9909-542436160c46\" name=\"files[]\" multiple disabled\n",
              "        style=\"border:none\" />\n",
              "     <output id=\"result-720fcddd-9fc2-4542-9909-542436160c46\">\n",
              "      Upload widget is only available when the cell has been executed in the\n",
              "      current browser session. Please rerun this cell to enable.\n",
              "      </output>\n",
              "      <script src=\"/nbextensions/google.colab/files.js\"></script> "
            ],
            "text/plain": [
              "<IPython.core.display.HTML object>"
            ]
          },
          "metadata": {
            "tags": []
          }
        },
        {
          "output_type": "stream",
          "text": [
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.SSLError'>\n",
            "args:(MaxRetryError(\"HTTPSConnectionPool(host='yukata.net', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))\",),)\n",
            "e自身:HTTPSConnectionPool(host='yukata.net', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))\n",
            "=== エラー内容 完 ===\n",
            "1 pass!\n",
            "2\n",
            "3\n",
            "4\n",
            "5\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.SSLError'>\n",
            "args:(MaxRetryError(\"HTTPSConnectionPool(host='www.zespri.com', port=443): Max retries exceeded with url: /ja-JP (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))\",),)\n",
            "e自身:HTTPSConnectionPool(host='www.zespri.com', port=443): Max retries exceeded with url: /ja-JP (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))\n",
            "=== エラー内容 完 ===\n",
            "6 pass!\n",
            "7\n",
            "8\n",
            "9\n",
            "10\n",
            "11\n",
            "12\n",
            "13\n",
            "14\n",
            "15\n",
            "16\n",
            "17\n",
            "18\n",
            "19\n",
            "20\n",
            "21\n",
            "22\n",
            "23\n",
            "24\n",
            "25\n",
            "26\n",
            "27\n",
            "28\n",
            "29\n",
            "30\n",
            "31\n",
            "32\n",
            "33\n",
            "34\n",
            "35\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectionError'>\n",
            "args:(MaxRetryError(\"HTTPSConnectionPool(host='www.verdureoffice.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7baee502b0>: Failed to establish a new connection: [Errno -2] Name or service not known',))\",),)\n",
            "e自身:HTTPSConnectionPool(host='www.verdureoffice.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7baee502b0>: Failed to establish a new connection: [Errno -2] Name or service not known',))\n",
            "=== エラー内容 完 ===\n",
            "36 pass!\n",
            "37\n",
            "38\n",
            "39\n",
            "40\n",
            "41\n",
            "42\n",
            "43\n",
            "44\n",
            "45\n",
            "46\n",
            "47\n",
            "48\n",
            "49\n",
            "50\n",
            "51\n",
            "52\n",
            "53\n",
            "54\n",
            "55\n",
            "56\n",
            "57\n",
            "58\n",
            "59\n",
            "60\n",
            "61\n",
            "62\n",
            "63\n",
            "64\n",
            "65\n",
            "66\n",
            "67\n",
            "68\n",
            "69\n",
            "70\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ReadTimeout'>\n",
            "args:(ReadTimeoutError(\"HTTPSConnectionPool(host='www.tonakaibin.com', port=443): Read timed out. (read timeout=10)\",),)\n",
            "e自身:HTTPSConnectionPool(host='www.tonakaibin.com', port=443): Read timed out. (read timeout=10)\n",
            "=== エラー内容 完 ===\n",
            "71 pass!\n",
            "72\n",
            "73\n",
            "74\n",
            "75\n",
            "76\n",
            "77\n",
            "78\n",
            "79\n",
            "80\n",
            "81\n",
            "82\n",
            "83\n",
            "84\n",
            "85\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.SSLError'>\n",
            "args:(MaxRetryError('HTTPSConnectionPool(host=\\'www.tl-trade.co.jp\\', port=443): Max retries exceeded with url: / (Caused by SSLError(CertificateError(\"hostname \\'www.tl-trade.co.jp\\' doesn\\'t match either of \\'*.domainserver.ne.jp\\', \\'domainserver.ne.jp\\'\",),))',),)\n",
            "e自身:HTTPSConnectionPool(host='www.tl-trade.co.jp', port=443): Max retries exceeded with url: / (Caused by SSLError(CertificateError(\"hostname 'www.tl-trade.co.jp' doesn't match either of '*.domainserver.ne.jp', 'domainserver.ne.jp'\",),))\n",
            "=== エラー内容 完 ===\n",
            "86 pass!\n",
            "87\n",
            "88\n",
            "89\n",
            "90\n",
            "91\n",
            "92\n",
            "93\n",
            "94\n",
            "95\n",
            "96\n",
            "97\n",
            "98\n",
            "99\n",
            "100\n",
            "101\n",
            "102\n",
            "103\n",
            "104\n",
            "105\n",
            "106\n",
            "107\n",
            "108\n",
            "109\n",
            "110\n",
            "111\n",
            "112\n",
            "113\n",
            "114\n",
            "115\n",
            "116\n",
            "117\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectionError'>\n",
            "args:(MaxRetryError(\"HTTPSConnectionPool(host='www.suisomeditec.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7baf123390>: Failed to establish a new connection: [Errno -2] Name or service not known',))\",),)\n",
            "e自身:HTTPSConnectionPool(host='www.suisomeditec.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7baf123390>: Failed to establish a new connection: [Errno -2] Name or service not known',))\n",
            "=== エラー内容 完 ===\n",
            "118 pass!\n",
            "119\n",
            "120\n",
            "121\n",
            "122\n",
            "123\n",
            "124\n",
            "125\n",
            "126\n",
            "127\n",
            "128\n",
            "129\n",
            "130\n",
            "131\n",
            "132\n",
            "133\n",
            "134\n",
            "135\n",
            "136\n",
            "137\n",
            "138\n",
            "139\n",
            "140\n",
            "141\n",
            "142\n",
            "143\n",
            "144\n",
            "145\n",
            "146\n",
            "147\n",
            "148\n",
            "149\n",
            "150\n",
            "151\n",
            "152\n",
            "153\n",
            "154\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.SSLError'>\n",
            "args:(MaxRetryError('HTTPSConnectionPool(host=\\'www.sera-wave.com\\', port=443): Max retries exceeded with url: / (Caused by SSLError(CertificateError(\"hostname \\'www.sera-wave.com\\' doesn\\'t match either of \\'*.secure.idchosting.jp\\', \\'secure.idchosting.jp\\'\",),))',),)\n",
            "e自身:HTTPSConnectionPool(host='www.sera-wave.com', port=443): Max retries exceeded with url: / (Caused by SSLError(CertificateError(\"hostname 'www.sera-wave.com' doesn't match either of '*.secure.idchosting.jp', 'secure.idchosting.jp'\",),))\n",
            "=== エラー内容 完 ===\n",
            "155 pass!\n",
            "156\n",
            "157\n",
            "158\n",
            "159\n",
            "160\n",
            "161\n",
            "162\n",
            "163\n",
            "164\n",
            "165\n",
            "166\n",
            "167\n",
            "168\n",
            "169\n",
            "170\n",
            "171\n",
            "172\n",
            "173\n",
            "174\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectionError'>\n",
            "args:(MaxRetryError(\"HTTPSConnectionPool(host='www.runway-japan.jp', port=443): Max retries exceeded with url: /home (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7baf70c198>: Failed to establish a new connection: [Errno -2] Name or service not known',))\",),)\n",
            "e自身:HTTPSConnectionPool(host='www.runway-japan.jp', port=443): Max retries exceeded with url: /home (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7baf70c198>: Failed to establish a new connection: [Errno -2] Name or service not known',))\n",
            "=== エラー内容 完 ===\n",
            "175 pass!\n",
            "176\n",
            "177\n",
            "178\n",
            "179\n",
            "180\n",
            "181\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectionError'>\n",
            "args:(MaxRetryError(\"HTTPSConnectionPool(host='www.r-next.co', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7bb01ede48>: Failed to establish a new connection: [Errno -2] Name or service not known',))\",),)\n",
            "e自身:HTTPSConnectionPool(host='www.r-next.co', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7bb01ede48>: Failed to establish a new connection: [Errno -2] Name or service not known',))\n",
            "=== エラー内容 完 ===\n",
            "182 pass!\n",
            "183\n",
            "184\n",
            "185\n",
            "186\n",
            "187\n",
            "188\n",
            "189\n",
            "190\n",
            "191\n",
            "192\n",
            "193\n",
            "194\n",
            "195\n",
            "196\n",
            "197\n",
            "198\n",
            "199\n",
            "200\n",
            "201\n",
            "202\n",
            "203\n",
            "204\n",
            "205\n",
            "206\n",
            "207\n",
            "208\n",
            "209\n",
            "210\n",
            "211\n",
            "212\n",
            "213\n",
            "214\n",
            "215\n",
            "216\n",
            "217\n",
            "218\n",
            "219\n",
            "220\n",
            "221\n",
            "222\n",
            "223\n",
            "224\n",
            "225\n",
            "226\n",
            "227\n",
            "228\n",
            "229\n",
            "230\n",
            "231\n",
            "232\n",
            "233\n",
            "234\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectionError'>\n",
            "args:(MaxRetryError(\"HTTPSConnectionPool(host='www.pucapuca.biz', port=443): Max retries exceeded with url: /online-shop/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7baf819080>: Failed to establish a new connection: [Errno -2] Name or service not known',))\",),)\n",
            "e自身:HTTPSConnectionPool(host='www.pucapuca.biz', port=443): Max retries exceeded with url: /online-shop/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7baf819080>: Failed to establish a new connection: [Errno -2] Name or service not known',))\n",
            "=== エラー内容 完 ===\n",
            "235 pass!\n",
            "236\n",
            "237\n",
            "238\n",
            "239\n",
            "240\n",
            "241\n",
            "242\n",
            "243\n",
            "244\n",
            "245\n",
            "246\n",
            "247\n",
            "248\n",
            "249\n",
            "250\n",
            "251\n",
            "252\n",
            "253\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectionError'>\n",
            "args:(MaxRetryError(\"HTTPSConnectionPool(host='www.perapera.online', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7bafae0320>: Failed to establish a new connection: [Errno -2] Name or service not known',))\",),)\n",
            "e自身:HTTPSConnectionPool(host='www.perapera.online', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7bafae0320>: Failed to establish a new connection: [Errno -2] Name or service not known',))\n",
            "=== エラー内容 完 ===\n",
            "254 pass!\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectionError'>\n",
            "args:(MaxRetryError(\"HTTPSConnectionPool(host='www.peace-rimland.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7baf6917f0>: Failed to establish a new connection: [Errno 111] Connection refused',))\",),)\n",
            "e自身:HTTPSConnectionPool(host='www.peace-rimland.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7baf6917f0>: Failed to establish a new connection: [Errno 111] Connection refused',))\n",
            "=== エラー内容 完 ===\n",
            "255 pass!\n",
            "256\n",
            "257\n",
            "258\n",
            "259\n",
            "260\n",
            "261\n",
            "262\n",
            "263\n",
            "264\n",
            "265\n",
            "266\n",
            "267\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.SSLError'>\n",
            "args:(MaxRetryError(\"HTTPSConnectionPool(host='www.optart.co.jp', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))\",),)\n",
            "e自身:HTTPSConnectionPool(host='www.optart.co.jp', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))\n",
            "=== エラー内容 完 ===\n",
            "268 pass!\n",
            "269\n",
            "270\n",
            "271\n",
            "272\n",
            "273\n",
            "274\n",
            "275\n",
            "276\n",
            "277\n",
            "278\n",
            "279\n",
            "280\n",
            "281\n",
            "282\n",
            "283\n",
            "284\n",
            "285\n",
            "286\n",
            "287\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.SSLError'>\n",
            "args:(MaxRetryError(\"HTTPSConnectionPool(host='www.nishinaga-medical.co.jp', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))\",),)\n",
            "e自身:HTTPSConnectionPool(host='www.nishinaga-medical.co.jp', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))\n",
            "=== エラー内容 完 ===\n",
            "288 pass!\n",
            "289\n",
            "290\n",
            "291\n",
            "292\n",
            "293\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.SSLError'>\n",
            "args:(MaxRetryError(\"HTTPSConnectionPool(host='www.nihon-ryutu.co.jp', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:852)'),))\",),)\n",
            "e自身:HTTPSConnectionPool(host='www.nihon-ryutu.co.jp', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:852)'),))\n",
            "=== エラー内容 完 ===\n",
            "294 pass!\n",
            "295\n",
            "296\n",
            "297\n",
            "298\n",
            "299\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectionError'>\n",
            "args:(MaxRetryError(\"HTTPSConnectionPool(host='www.next777.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7baf93fa58>: Failed to establish a new connection: [Errno -2] Name or service not known',))\",),)\n",
            "e自身:HTTPSConnectionPool(host='www.next777.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7baf93fa58>: Failed to establish a new connection: [Errno -2] Name or service not known',))\n",
            "=== エラー内容 完 ===\n",
            "300 pass!\n",
            "301\n",
            "302\n",
            "303\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.SSLError'>\n",
            "args:(MaxRetryError('HTTPSConnectionPool(host=\\'www.newstrading.biz\\', port=443): Max retries exceeded with url: / (Caused by SSLError(CertificateError(\"hostname \\'www.newstrading.biz\\' doesn\\'t match either of \\'*.sakura.ne.jp\\', \\'*.180r.com\\', \\'*.2-d.jp\\', \\'*.achoo.jp\\', \\'*.amaretto.jp\\', \\'*.bona.jp\\', \\'*.chew.jp\\', \\'*.crap.jp\\', \\'*.daynight.jp\\', \\'*.deko8.jp\\', \\'*.dojin.com\\', \\'*.eek.jp\\', \\'*.flop.jp\\', \\'*.from.tv\\', \\'*.fubuki.info\\', \\'*.gokujou.biz\\', \\'*.grats.jp\\', \\'*.grrr.jp\\', \\'*.halfmoon.jp\\', \\'*.ivory.ne.jp\\', \\'*.jeez.jp\\', \\'*.jpn.org\\', \\'*.kirara.st\\', \\'*.kokage.cc\\', \\'*.mail-box.ne.jp\\', \\'*.matrix.jp\\', \\'*.mimoza.jp\\', \\'*.mints.ne.jp\\', \\'*.mokuren.ne.jp\\', \\'*.nazo.cc\\', \\'*.netgamers.jp\\', \\'*.noob.jp\\', \\'*.nyanta.jp\\', \\'*.o0o0.jp\\', \\'*.opal.ne.jp\\', \\'*.rash.jp\\', \\'*.razor.jp\\', \\'*.rdy.jp\\', \\'*.rgr.jp\\', \\'*.rojo.jp\\', \\'*.rossa.cc\\', \\'*.rulez.jp\\', \\'*.rusk.to\\', \\'*.saikyou.biz\\', \\'*.sakura.tv\\', \\'*.sakuratan.com\\', \\'*.sakuraweb.com\\', \\'*.saloon.jp\\', \\'*.silk.to\\', \\'*.skr.jp\\', \\'*.spawn.jp\\', \\'*.squares.net\\', \\'*.sumomo.ne.jp\\', \\'*.tank.jp\\', \\'*.thyme.jp\\', \\'*.topaz.ne.jp\\', \\'*.uh-oh.jp\\', \\'*.undo.jp\\', \\'*.websozai.jp\\', \\'*.whoa.jp\\', \\'*.x0.com\\', \\'*.x0.to\\', \\'*.xii.jp\\'\",),))',),)\n",
            "e自身:HTTPSConnectionPool(host='www.newstrading.biz', port=443): Max retries exceeded with url: / (Caused by SSLError(CertificateError(\"hostname 'www.newstrading.biz' doesn't match either of '*.sakura.ne.jp', '*.180r.com', '*.2-d.jp', '*.achoo.jp', '*.amaretto.jp', '*.bona.jp', '*.chew.jp', '*.crap.jp', '*.daynight.jp', '*.deko8.jp', '*.dojin.com', '*.eek.jp', '*.flop.jp', '*.from.tv', '*.fubuki.info', '*.gokujou.biz', '*.grats.jp', '*.grrr.jp', '*.halfmoon.jp', '*.ivory.ne.jp', '*.jeez.jp', '*.jpn.org', '*.kirara.st', '*.kokage.cc', '*.mail-box.ne.jp', '*.matrix.jp', '*.mimoza.jp', '*.mints.ne.jp', '*.mokuren.ne.jp', '*.nazo.cc', '*.netgamers.jp', '*.noob.jp', '*.nyanta.jp', '*.o0o0.jp', '*.opal.ne.jp', '*.rash.jp', '*.razor.jp', '*.rdy.jp', '*.rgr.jp', '*.rojo.jp', '*.rossa.cc', '*.rulez.jp', '*.rusk.to', '*.saikyou.biz', '*.sakura.tv', '*.sakuratan.com', '*.sakuraweb.com', '*.saloon.jp', '*.silk.to', '*.skr.jp', '*.spawn.jp', '*.squares.net', '*.sumomo.ne.jp', '*.tank.jp', '*.thyme.jp', '*.topaz.ne.jp', '*.uh-oh.jp', '*.undo.jp', '*.websozai.jp', '*.whoa.jp', '*.x0.com', '*.x0.to', '*.xii.jp'\",),))\n",
            "=== エラー内容 完 ===\n",
            "304 pass!\n",
            "305\n",
            "306\n",
            "307\n",
            "308\n",
            "309\n",
            "310\n",
            "311\n",
            "312\n",
            "313\n",
            "314\n",
            "315\n",
            "316\n",
            "317\n",
            "318\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectionError'>\n",
            "args:(MaxRetryError(\"HTTPSConnectionPool(host='www.mtm-tokyo.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7baee17780>: Failed to establish a new connection: [Errno -2] Name or service not known',))\",),)\n",
            "e自身:HTTPSConnectionPool(host='www.mtm-tokyo.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7baee17780>: Failed to establish a new connection: [Errno -2] Name or service not known',))\n",
            "=== エラー内容 完 ===\n",
            "319 pass!\n",
            "320\n",
            "321\n",
            "322\n",
            "323\n",
            "324\n",
            "325\n",
            "326\n",
            "327\n",
            "328\n",
            "329\n",
            "330\n",
            "331\n",
            "332\n",
            "333\n",
            "334\n",
            "335\n",
            "336\n",
            "337\n",
            "338\n",
            "339\n",
            "340\n",
            "341\n",
            "342\n",
            "343\n",
            "344\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectTimeout'>\n",
            "args:(MaxRetryError(\"HTTPSConnectionPool(host='www.medelu.flowers', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7bb00e6be0>, 'Connection to www.medelu.flowers timed out. (connect timeout=10)'))\",),)\n",
            "e自身:HTTPSConnectionPool(host='www.medelu.flowers', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7bb00e6be0>, 'Connection to www.medelu.flowers timed out. (connect timeout=10)'))\n",
            "=== エラー内容 完 ===\n",
            "345 pass!\n",
            "346\n",
            "347\n",
            "348\n",
            "349\n",
            "350\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectionError'>\n",
            "args:(MaxRetryError(\"HTTPSConnectionPool(host='www.mast-kiya.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7baf0ca6a0>: Failed to establish a new connection: [Errno -2] Name or service not known',))\",),)\n",
            "e自身:HTTPSConnectionPool(host='www.mast-kiya.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7baf0ca6a0>: Failed to establish a new connection: [Errno -2] Name or service not known',))\n",
            "=== エラー内容 完 ===\n",
            "351 pass!\n",
            "352\n",
            "353\n",
            "354\n",
            "355\n",
            "356\n",
            "357\n",
            "358\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.SSLError'>\n",
            "args:(MaxRetryError('HTTPSConnectionPool(host=\\'www.mamegyorai.co.jp\\', port=443): Max retries exceeded with url: /net/default.aspx (Caused by SSLError(CertificateError(\"hostname \\'www.mamegyorai.co.jp\\' doesn\\'t match either of \\'mamegyorai.jp\\', \\'www.mamegyorai.jp\\'\",),))',),)\n",
            "e自身:HTTPSConnectionPool(host='www.mamegyorai.co.jp', port=443): Max retries exceeded with url: /net/default.aspx (Caused by SSLError(CertificateError(\"hostname 'www.mamegyorai.co.jp' doesn't match either of 'mamegyorai.jp', 'www.mamegyorai.jp'\",),))\n",
            "=== エラー内容 完 ===\n",
            "359 pass!\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectTimeout'>\n",
            "args:(MaxRetryError(\"HTTPSConnectionPool(host='www.malucane.co.jp', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7baf9208d0>, 'Connection to www.malucane.co.jp timed out. (connect timeout=10)'))\",),)\n",
            "e自身:HTTPSConnectionPool(host='www.malucane.co.jp', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7baf9208d0>, 'Connection to www.malucane.co.jp timed out. (connect timeout=10)'))\n",
            "=== エラー内容 完 ===\n",
            "360 pass!\n",
            "361\n",
            "362\n",
            "363\n",
            "364\n",
            "365\n",
            "366\n",
            "367\n",
            "368\n",
            "369\n",
            "370\n",
            "371\n",
            "372\n",
            "373\n",
            "374\n",
            "375\n",
            "376\n",
            "377\n",
            "378\n",
            "379\n",
            "380\n",
            "381\n",
            "382\n",
            "383\n",
            "384\n",
            "385\n",
            "386\n",
            "387\n",
            "388\n",
            "389\n",
            "390\n",
            "391\n",
            "392\n",
            "393\n",
            "394\n",
            "395\n",
            "396\n",
            "397\n",
            "398\n",
            "399\n",
            "400\n",
            "401\n",
            "402\n",
            "403\n",
            "404\n",
            "405\n",
            "406\n",
            "407\n",
            "408\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectionError'>\n",
            "args:(MaxRetryError(\"HTTPSConnectionPool(host='www.kdijpn.co.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7baf72d710>: Failed to establish a new connection: [Errno -2] Name or service not known',))\",),)\n",
            "e自身:HTTPSConnectionPool(host='www.kdijpn.co.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7baf72d710>: Failed to establish a new connection: [Errno -2] Name or service not known',))\n",
            "=== エラー内容 完 ===\n",
            "409 pass!\n",
            "410\n",
            "411\n",
            "412\n",
            "413\n",
            "414\n",
            "415\n",
            "416\n",
            "417\n",
            "418\n",
            "419\n",
            "420\n",
            "421\n",
            "422\n",
            "423\n",
            "424\n",
            "425\n",
            "426\n",
            "427\n",
            "428\n",
            "429\n",
            "430\n",
            "431\n",
            "432\n",
            "433\n",
            "434\n",
            "435\n",
            "436\n",
            "437\n",
            "438\n",
            "439\n",
            "440\n",
            "441\n",
            "442\n",
            "443\n",
            "444\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectionError'>\n",
            "args:(MaxRetryError(\"HTTPSConnectionPool(host='www.itokinfun.co.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7baeecc550>: Failed to establish a new connection: [Errno -2] Name or service not known',))\",),)\n",
            "e自身:HTTPSConnectionPool(host='www.itokinfun.co.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7baeecc550>: Failed to establish a new connection: [Errno -2] Name or service not known',))\n",
            "=== エラー内容 完 ===\n",
            "445 pass!\n",
            "446\n",
            "447\n",
            "448\n",
            "449\n",
            "450\n",
            "451\n",
            "452\n",
            "453\n",
            "454\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectionError'>\n",
            "args:(MaxRetryError(\"HTTPSConnectionPool(host='www.inababag.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7baeecc710>: Failed to establish a new connection: [Errno -2] Name or service not known',))\",),)\n",
            "e自身:HTTPSConnectionPool(host='www.inababag.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7baeecc710>: Failed to establish a new connection: [Errno -2] Name or service not known',))\n",
            "=== エラー内容 完 ===\n",
            "455 pass!\n",
            "456\n",
            "457\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.SSLError'>\n",
            "args:(MaxRetryError(\"HTTPSConnectionPool(host='www.ihdc.co.jp', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))\",),)\n",
            "e自身:HTTPSConnectionPool(host='www.ihdc.co.jp', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))\n",
            "=== エラー内容 完 ===\n",
            "458 pass!\n",
            "459\n",
            "460\n",
            "461\n",
            "462\n",
            "463\n",
            "464\n",
            "465\n",
            "466\n",
            "467\n",
            "468\n",
            "469\n",
            "470\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.SSLError'>\n",
            "args:(MaxRetryError(\"HTTPSConnectionPool(host='www.hatebur.com', port=443): Max retries exceeded with url: /ja/ (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))\",),)\n",
            "e自身:HTTPSConnectionPool(host='www.hatebur.com', port=443): Max retries exceeded with url: /ja/ (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))\n",
            "=== エラー内容 完 ===\n",
            "471 pass!\n",
            "472\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.SSLError'>\n",
            "args:(MaxRetryError(\"HTTPSConnectionPool(host='www.happinet.co.jp', port=443): Max retries exceeded with url: /company/group.html (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))\",),)\n",
            "e自身:HTTPSConnectionPool(host='www.happinet.co.jp', port=443): Max retries exceeded with url: /company/group.html (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))\n",
            "=== エラー内容 完 ===\n",
            "473 pass!\n",
            "474\n",
            "475\n",
            "476\n",
            "477\n",
            "478\n",
            "479\n",
            "480\n",
            "481\n",
            "482\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.SSLError'>\n",
            "args:(MaxRetryError(\"HTTPSConnectionPool(host='www.goodfellows.co.jp', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))\",),)\n",
            "e自身:HTTPSConnectionPool(host='www.goodfellows.co.jp', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))\n",
            "=== エラー内容 完 ===\n",
            "483 pass!\n",
            "484\n",
            "485\n",
            "486\n",
            "487\n",
            "488\n",
            "489\n",
            "490\n",
            "491\n",
            "492\n",
            "493\n",
            "494\n",
            "495\n",
            "496\n",
            "497\n",
            "498\n",
            "499\n",
            "500\n",
            "501\n",
            "502\n",
            "503\n",
            "504\n",
            "505\n",
            "506\n",
            "507\n",
            "508\n",
            "509\n",
            "510\n",
            "511\n",
            "512\n",
            "513\n",
            "514\n",
            "515\n",
            "516\n",
            "517\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectionError'>\n",
            "args:(MaxRetryError(\"HTTPSConnectionPool(host='www.fci-products.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7bafa2f400>: Failed to establish a new connection: [Errno -2] Name or service not known',))\",),)\n",
            "e自身:HTTPSConnectionPool(host='www.fci-products.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7bafa2f400>: Failed to establish a new connection: [Errno -2] Name or service not known',))\n",
            "=== エラー内容 完 ===\n",
            "518 pass!\n",
            "519\n",
            "520\n",
            "521\n",
            "522\n",
            "523\n",
            "524\n",
            "525\n",
            "526\n",
            "527\n",
            "528\n",
            "529\n",
            "530\n",
            "531\n",
            "532\n",
            "533\n",
            "534\n",
            "535\n",
            "536\n",
            "537\n",
            "538\n",
            "539\n",
            "540\n",
            "541\n",
            "542\n",
            "543\n",
            "544\n",
            "545\n",
            "546\n",
            "547\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.SSLError'>\n",
            "args:(MaxRetryError(\"HTTPSConnectionPool(host='www.dmi.co.jp', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))\",),)\n",
            "e自身:HTTPSConnectionPool(host='www.dmi.co.jp', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))\n",
            "=== エラー内容 完 ===\n",
            "548 pass!\n",
            "549\n",
            "550\n",
            "551\n",
            "552\n",
            "553\n",
            "554\n",
            "555\n",
            "556\n",
            "557\n",
            "558\n",
            "559\n",
            "560\n",
            "561\n",
            "562\n",
            "563\n",
            "564\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectionError'>\n",
            "args:(MaxRetryError(\"HTTPSConnectionPool(host='www.couleure.co.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7baeaf25c0>: Failed to establish a new connection: [Errno -2] Name or service not known',))\",),)\n",
            "e自身:HTTPSConnectionPool(host='www.couleure.co.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7baeaf25c0>: Failed to establish a new connection: [Errno -2] Name or service not known',))\n",
            "=== エラー内容 完 ===\n",
            "565 pass!\n",
            "566\n",
            "567\n",
            "568\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.SSLError'>\n",
            "args:(MaxRetryError(\"HTTPSConnectionPool(host='www.chukoh-belt.co.jp', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))\",),)\n",
            "e自身:HTTPSConnectionPool(host='www.chukoh-belt.co.jp', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))\n",
            "=== エラー内容 完 ===\n",
            "569 pass!\n",
            "570\n",
            "571\n",
            "572\n",
            "573\n",
            "574\n",
            "575\n",
            "576\n",
            "577\n",
            "578\n",
            "579\n",
            "580\n",
            "581\n",
            "582\n",
            "583\n",
            "584\n",
            "585\n",
            "586\n",
            "587\n",
            "588\n",
            "589\n",
            "590\n",
            "591\n",
            "592\n",
            "593\n",
            "594\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectionError'>\n",
            "args:(MaxRetryError(\"HTTPSConnectionPool(host='www.bigplanet-inc.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7baf73d400>: Failed to establish a new connection: [Errno -2] Name or service not known',))\",),)\n",
            "e自身:HTTPSConnectionPool(host='www.bigplanet-inc.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7baf73d400>: Failed to establish a new connection: [Errno -2] Name or service not known',))\n",
            "=== エラー内容 完 ===\n",
            "595 pass!\n",
            "596\n",
            "597\n",
            "598\n",
            "599\n",
            "600\n",
            "601\n",
            "602\n",
            "603\n",
            "604\n",
            "605\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectionError'>\n",
            "args:(MaxRetryError(\"HTTPSConnectionPool(host='www.bansei21.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7baf4fd8d0>: Failed to establish a new connection: [Errno -2] Name or service not known',))\",),)\n",
            "e自身:HTTPSConnectionPool(host='www.bansei21.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7baf4fd8d0>: Failed to establish a new connection: [Errno -2] Name or service not known',))\n",
            "=== エラー内容 完 ===\n",
            "606 pass!\n",
            "607\n",
            "608\n",
            "609\n",
            "610\n",
            "611\n",
            "612\n",
            "613\n",
            "614\n",
            "615\n",
            "616\n",
            "617\n",
            "618\n",
            "619\n",
            "620\n",
            "621\n",
            "622\n",
            "623\n",
            "624\n",
            "625\n",
            "626\n",
            "627\n",
            "628\n",
            "629\n",
            "630\n",
            "631\n",
            "632\n",
            "633\n",
            "634\n",
            "635\n",
            "636\n",
            "637\n",
            "638\n",
            "639\n",
            "640\n",
            "641\n",
            "642\n",
            "643\n",
            "644\n",
            "645\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectionError'>\n",
            "args:(MaxRetryError(\"HTTPSConnectionPool(host='www.almasllc.info', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7baf06ce48>: Failed to establish a new connection: [Errno -2] Name or service not known',))\",),)\n",
            "e自身:HTTPSConnectionPool(host='www.almasllc.info', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7baf06ce48>: Failed to establish a new connection: [Errno -2] Name or service not known',))\n",
            "=== エラー内容 完 ===\n",
            "646 pass!\n",
            "647\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.SSLError'>\n",
            "args:(MaxRetryError(\"HTTPSConnectionPool(host='www.alba-beauty.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:852)'),))\",),)\n",
            "e自身:HTTPSConnectionPool(host='www.alba-beauty.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:852)'),))\n",
            "=== エラー内容 完 ===\n",
            "648 pass!\n",
            "649\n",
            "650\n",
            "651\n",
            "652\n",
            "653\n",
            "654\n",
            "655\n",
            "656\n",
            "657\n",
            "658\n",
            "659\n",
            "660\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectionError'>\n",
            "args:(MaxRetryError(\"HTTPSConnectionPool(host='www.abcd-p.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7badf11cc0>: Failed to establish a new connection: [Errno -5] No address associated with hostname',))\",),)\n",
            "e自身:HTTPSConnectionPool(host='www.abcd-p.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7badf11cc0>: Failed to establish a new connection: [Errno -5] No address associated with hostname',))\n",
            "=== エラー内容 完 ===\n",
            "661 pass!\n",
            "662\n",
            "663\n",
            "664\n",
            "665\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.SSLError'>\n",
            "args:(MaxRetryError(\"HTTPSConnectionPool(host='wururu.jp', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))\",),)\n",
            "e自身:HTTPSConnectionPool(host='wururu.jp', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))\n",
            "=== エラー内容 完 ===\n",
            "666 pass!\n",
            "667\n",
            "668\n",
            "669\n",
            "670\n",
            "671\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectionError'>\n",
            "args:(MaxRetryError(\"HTTPSConnectionPool(host='victor-corp.co.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7bae09f390>: Failed to establish a new connection: [Errno -2] Name or service not known',))\",),)\n",
            "e自身:HTTPSConnectionPool(host='victor-corp.co.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7bae09f390>: Failed to establish a new connection: [Errno -2] Name or service not known',))\n",
            "=== エラー内容 完 ===\n",
            "672 pass!\n",
            "673\n",
            "674\n",
            "675\n",
            "676\n",
            "677\n",
            "678\n",
            "679\n",
            "680\n",
            "681\n",
            "682\n",
            "683\n",
            "684\n",
            "685\n",
            "686\n",
            "687\n",
            "688\n",
            "689\n",
            "690\n",
            "691\n",
            "692\n",
            "693\n",
            "694\n",
            "695\n",
            "696\n",
            "697\n",
            "698\n",
            "699\n",
            "700\n",
            "701\n",
            "702\n",
            "703\n",
            "704\n",
            "705\n",
            "706\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectionError'>\n",
            "args:(MaxRetryError(\"HTTPSConnectionPool(host='ss-search.emg-ss.jp', port=443): Max retries exceeded with url: /b/emg/info/312034/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7baed4c438>: Failed to establish a new connection: [Errno -2] Name or service not known',))\",),)\n",
            "e自身:HTTPSConnectionPool(host='ss-search.emg-ss.jp', port=443): Max retries exceeded with url: /b/emg/info/312034/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7baed4c438>: Failed to establish a new connection: [Errno -2] Name or service not known',))\n",
            "=== エラー内容 完 ===\n",
            "707 pass!\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectTimeout'>\n",
            "args:(MaxRetryError(\"HTTPSConnectionPool(host='ssl.auq.jp', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7baed4c3c8>, 'Connection to ssl.auq.jp timed out. (connect timeout=10)'))\",),)\n",
            "e自身:HTTPSConnectionPool(host='ssl.auq.jp', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7baed4c3c8>, 'Connection to ssl.auq.jp timed out. (connect timeout=10)'))\n",
            "=== エラー内容 完 ===\n",
            "708 pass!\n",
            "709\n",
            "710\n",
            "711\n",
            "712\n",
            "713\n",
            "714\n",
            "715\n",
            "716\n",
            "717\n",
            "718\n",
            "719\n",
            "720\n",
            "721\n",
            "722\n",
            "723\n",
            "724\n",
            "725\n",
            "726\n",
            "727\n",
            "728\n",
            "729\n",
            "730\n",
            "731\n",
            "732\n",
            "733\n",
            "734\n",
            "735\n",
            "736\n",
            "737\n",
            "738\n",
            "739\n",
            "740\n",
            "741\n",
            "742\n",
            "743\n",
            "744\n",
            "745\n",
            "746\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectionError'>\n",
            "args:(MaxRetryError(\"HTTPSConnectionPool(host='rakusuri.co.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7baec98be0>: Failed to establish a new connection: [Errno -2] Name or service not known',))\",),)\n",
            "e自身:HTTPSConnectionPool(host='rakusuri.co.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7baec98be0>: Failed to establish a new connection: [Errno -2] Name or service not known',))\n",
            "=== エラー内容 完 ===\n",
            "747 pass!\n",
            "748\n",
            "749\n",
            "750\n",
            "751\n",
            "752\n",
            "753\n",
            "754\n",
            "755\n",
            "756\n",
            "757\n",
            "758\n",
            "759\n",
            "760\n",
            "761\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ReadTimeout'>\n",
            "args:(ReadTimeoutError(\"HTTPSConnectionPool(host='onze1852.co.jp', port=443): Read timed out. (read timeout=10)\",),)\n",
            "e自身:HTTPSConnectionPool(host='onze1852.co.jp', port=443): Read timed out. (read timeout=10)\n",
            "=== エラー内容 完 ===\n",
            "762 pass!\n",
            "763\n",
            "764\n",
            "765\n",
            "766\n",
            "767\n",
            "768\n",
            "769\n",
            "770\n",
            "771\n",
            "772\n",
            "773\n",
            "774\n",
            "775\n",
            "776\n",
            "777\n",
            "778\n",
            "779\n",
            "780\n",
            "781\n",
            "782\n",
            "783\n",
            "784\n",
            "785\n",
            "786\n",
            "787\n",
            "788\n",
            "789\n",
            "790\n",
            "791\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.SSLError'>\n",
            "args:(MaxRetryError('HTTPSConnectionPool(host=\\'maunaloa-mmj.jp\\', port=443): Max retries exceeded with url: / (Caused by SSLError(CertificateError(\"hostname \\'maunaloa-mmj.jp\\' doesn\\'t match either of \\'*.i-do.ne.jp\\', \\'i-do.ne.jp\\'\",),))',),)\n",
            "e自身:HTTPSConnectionPool(host='maunaloa-mmj.jp', port=443): Max retries exceeded with url: / (Caused by SSLError(CertificateError(\"hostname 'maunaloa-mmj.jp' doesn't match either of '*.i-do.ne.jp', 'i-do.ne.jp'\",),))\n",
            "=== エラー内容 完 ===\n",
            "792 pass!\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.SSLError'>\n",
            "args:(MaxRetryError(\"HTTPSConnectionPool(host='matrix-aida.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))\",),)\n",
            "e自身:HTTPSConnectionPool(host='matrix-aida.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))\n",
            "=== エラー内容 完 ===\n",
            "793 pass!\n",
            "794\n",
            "795\n",
            "796\n",
            "797\n",
            "798\n",
            "799\n",
            "800\n",
            "801\n",
            "802\n",
            "803\n",
            "804\n",
            "805\n",
            "806\n",
            "807\n",
            "808\n",
            "809\n",
            "810\n",
            "811\n",
            "812\n",
            "813\n",
            "814\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectionError'>\n",
            "args:(MaxRetryError(\"HTTPSConnectionPool(host='kodakara.co.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7baefd7828>: Failed to establish a new connection: [Errno -2] Name or service not known',))\",),)\n",
            "e自身:HTTPSConnectionPool(host='kodakara.co.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7baefd7828>: Failed to establish a new connection: [Errno -2] Name or service not known',))\n",
            "=== エラー内容 完 ===\n",
            "815 pass!\n",
            "816\n",
            "817\n",
            "818\n",
            "819\n",
            "820\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectionError'>\n",
            "args:(MaxRetryError(\"HTTPSConnectionPool(host='kawaikabu.sharepoint.com', port=443): Max retries exceeded with url: /Pages/default.aspx (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7baf0ea4a8>: Failed to establish a new connection: [Errno -2] Name or service not known',))\",),)\n",
            "e自身:HTTPSConnectionPool(host='kawaikabu.sharepoint.com', port=443): Max retries exceeded with url: /Pages/default.aspx (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7baf0ea4a8>: Failed to establish a new connection: [Errno -2] Name or service not known',))\n",
            "=== エラー内容 完 ===\n",
            "821 pass!\n",
            "822\n",
            "823\n",
            "824\n",
            "825\n",
            "826\n",
            "827\n",
            "828\n",
            "829\n",
            "830\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ReadTimeout'>\n",
            "args:(ReadTimeoutError(\"HTTPSConnectionPool(host='jp.ert.com', port=443): Read timed out. (read timeout=10)\",),)\n",
            "e自身:HTTPSConnectionPool(host='jp.ert.com', port=443): Read timed out. (read timeout=10)\n",
            "=== エラー内容 完 ===\n",
            "831 pass!\n",
            "832\n",
            "833\n",
            "834\n",
            "835\n",
            "836\n",
            "837\n",
            "838\n",
            "839\n",
            "840\n",
            "841\n",
            "842\n",
            "843\n",
            "844\n",
            "845\n",
            "846\n",
            "847\n",
            "848\n",
            "849\n",
            "850\n",
            "851\n",
            "852\n",
            "853\n",
            "854\n",
            "855\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.SSLError'>\n",
            "args:(MaxRetryError(\"HTTPSConnectionPool(host='hellsen.co.jp', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))\",),)\n",
            "e自身:HTTPSConnectionPool(host='hellsen.co.jp', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))\n",
            "=== エラー内容 完 ===\n",
            "856 pass!\n",
            "857\n",
            "858\n",
            "859\n",
            "860\n",
            "861\n",
            "862\n",
            "863\n",
            "864\n",
            "865\n",
            "866\n",
            "867\n",
            "868\n",
            "869\n",
            "870\n",
            "871\n",
            "872\n",
            "873\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.SSLError'>\n",
            "args:(MaxRetryError(\"HTTPSConnectionPool(host='fro-factory.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))\",),)\n",
            "e自身:HTTPSConnectionPool(host='fro-factory.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))\n",
            "=== エラー内容 完 ===\n",
            "874 pass!\n",
            "875\n",
            "876\n",
            "877\n",
            "878\n",
            "879\n",
            "880\n",
            "881\n",
            "882\n",
            "883\n",
            "884\n",
            "885\n",
            "886\n",
            "887\n",
            "888\n",
            "889\n",
            "890\n",
            "891\n",
            "892\n",
            "893\n",
            "894\n",
            "895\n",
            "896\n",
            "897\n",
            "898\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectionError'>\n",
            "args:(MaxRetryError(\"HTTPSConnectionPool(host='create-aol.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7bae065f28>: Failed to establish a new connection: [Errno -5] No address associated with hostname',))\",),)\n",
            "e自身:HTTPSConnectionPool(host='create-aol.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7bae065f28>: Failed to establish a new connection: [Errno -5] No address associated with hostname',))\n",
            "=== エラー内容 完 ===\n",
            "899 pass!\n",
            "900\n",
            "901\n",
            "902\n",
            "903\n",
            "904\n",
            "905\n",
            "906\n",
            "907\n",
            "908\n",
            "909\n",
            "910\n",
            "911\n",
            "912\n",
            "913\n",
            "914\n",
            "915\n",
            "916\n",
            "917\n",
            "918\n",
            "919\n",
            "920\n",
            "921\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectTimeout'>\n",
            "args:(MaxRetryError(\"HTTPSConnectionPool(host='av-ueno.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7bb0334710>, 'Connection to av-ueno.com timed out. (connect timeout=10)'))\",),)\n",
            "e自身:HTTPSConnectionPool(host='av-ueno.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7bb0334710>, 'Connection to av-ueno.com timed out. (connect timeout=10)'))\n",
            "=== エラー内容 完 ===\n",
            "922 pass!\n",
            "923\n",
            "924\n",
            "925\n",
            "926\n",
            "927\n",
            "928\n",
            "929\n",
            "930\n",
            "931\n",
            "932\n",
            "933\n",
            "934\n",
            "935\n",
            "936\n",
            "937\n",
            "938\n",
            "939\n",
            "940\n",
            "941\n",
            "942\n",
            "943\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectTimeout'>\n",
            "args:(MaxRetryError(\"HTTPSConnectionPool(host='3219.cc', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7bae067240>, 'Connection to 3219.cc timed out. (connect timeout=10)'))\",),)\n",
            "e自身:HTTPSConnectionPool(host='3219.cc', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7bae067240>, 'Connection to 3219.cc timed out. (connect timeout=10)'))\n",
            "=== エラー内容 完 ===\n",
            "944 pass!\n",
            "945\n",
            "946\n",
            "947\n",
            "948\n",
            "949\n",
            "950\n",
            "951\n",
            "952\n",
            "953\n",
            "954\n",
            "955\n",
            "956\n",
            "957\n",
            "958\n",
            "959\n",
            "960\n",
            "961\n",
            "962\n",
            "963\n",
            "964\n",
            "965\n",
            "966\n",
            "967\n",
            "968\n",
            "969\n",
            "970\n",
            "971\n",
            "972\n",
            "973\n",
            "974\n",
            "975\n",
            "976\n",
            "977\n",
            "978\n",
            "979\n",
            "980\n",
            "981\n",
            "982\n",
            "983\n",
            "984\n",
            "985\n",
            "986\n",
            "987\n",
            "988\n",
            "989\n",
            "990\n",
            "991\n",
            "992\n",
            "993\n",
            "994\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectionError'>\n",
            "args:(MaxRetryError(\"HTTPConnectionPool(host='yamato-kohsan.jp', port=80): Max retries exceeded with url: /ec/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7bb028e400>: Failed to establish a new connection: [Errno -2] Name or service not known',))\",),)\n",
            "e自身:HTTPConnectionPool(host='yamato-kohsan.jp', port=80): Max retries exceeded with url: /ec/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7bb028e400>: Failed to establish a new connection: [Errno -2] Name or service not known',))\n",
            "=== エラー内容 完 ===\n",
            "995 pass!\n",
            "996\n",
            "997\n",
            "998\n",
            "999\n",
            "1000\n",
            "1001\n",
            "1002\n",
            "1003\n",
            "1004\n",
            "1005\n",
            "1006\n",
            "1007\n",
            "1008\n",
            "1009\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectionError'>\n",
            "args:(MaxRetryError(\"HTTPConnectionPool(host='xlight.co.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7baee63fd0>: Failed to establish a new connection: [Errno -2] Name or service not known',))\",),)\n",
            "e自身:HTTPConnectionPool(host='xlight.co.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7baee63fd0>: Failed to establish a new connection: [Errno -2] Name or service not known',))\n",
            "=== エラー内容 完 ===\n",
            "1010 pass!\n",
            "1011\n",
            "1012\n",
            "1013\n",
            "1014\n",
            "1015\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectionError'>\n",
            "args:(MaxRetryError(\"HTTPConnectionPool(host='www7.ocn.ne.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7baed36518>: Failed to establish a new connection: [Errno -2] Name or service not known',))\",),)\n",
            "e自身:HTTPConnectionPool(host='www7.ocn.ne.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7baed36518>: Failed to establish a new connection: [Errno -2] Name or service not known',))\n",
            "=== エラー内容 完 ===\n",
            "1016 pass!\n",
            "1017\n",
            "1018\n",
            "1019\n",
            "1020\n",
            "1021\n",
            "1022\n",
            "1023\n",
            "1024\n",
            "1025\n",
            "1026\n",
            "1027\n",
            "1028\n",
            "1029\n",
            "1030\n",
            "1031\n",
            "1032\n",
            "1033\n",
            "1034\n",
            "1035\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectionError'>\n",
            "args:(MaxRetryError(\"HTTPConnectionPool(host='www1a.biglobe.ne.jp', port=80): Max retries exceeded with url: /fbcinternational/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7bafb47240>: Failed to establish a new connection: [Errno -2] Name or service not known',))\",),)\n",
            "e自身:HTTPConnectionPool(host='www1a.biglobe.ne.jp', port=80): Max retries exceeded with url: /fbcinternational/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7bafb47240>: Failed to establish a new connection: [Errno -2] Name or service not known',))\n",
            "=== エラー内容 完 ===\n",
            "1036 pass!\n",
            "1037\n",
            "1038\n",
            "1039\n",
            "1040\n",
            "1041\n",
            "1042\n",
            "1043\n",
            "1044\n",
            "1045\n",
            "1046\n",
            "1047\n",
            "1048\n",
            "1049\n",
            "1050\n",
            "1051\n",
            "1052\n",
            "1053\n",
            "1054\n",
            "1055\n",
            "1056\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectionError'>\n",
            "args:(MaxRetryError(\"HTTPConnectionPool(host='www.zoro-shop.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7baef0b358>: Failed to establish a new connection: [Errno -2] Name or service not known',))\",),)\n",
            "e自身:HTTPConnectionPool(host='www.zoro-shop.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7baef0b358>: Failed to establish a new connection: [Errno -2] Name or service not known',))\n",
            "=== エラー内容 完 ===\n",
            "1057 pass!\n",
            "1058\n",
            "1059\n",
            "1060\n",
            "1061\n",
            "1062\n",
            "1063\n",
            "1064\n",
            "1065\n",
            "1066\n",
            "1067\n",
            "1068\n",
            "1069\n",
            "1070\n",
            "1071\n",
            "1072\n",
            "1073\n",
            "1074\n",
            "1075\n",
            "1076\n",
            "1077\n",
            "1078\n",
            "1079\n",
            "1080\n",
            "1081\n",
            "1082\n",
            "1083\n",
            "1084\n",
            "1085\n",
            "1086\n",
            "1087\n",
            "1088\n",
            "1089\n",
            "1090\n",
            "1091\n",
            "1092\n",
            "1093\n",
            "1094\n",
            "1095\n",
            "1096\n",
            "1097\n",
            "1098\n",
            "1099\n",
            "1100\n",
            "1101\n",
            "1102\n",
            "1103\n",
            "1104\n",
            "1105\n",
            "1106\n",
            "1107\n",
            "1108\n",
            "1109\n",
            "1110\n",
            "1111\n",
            "1112\n",
            "1113\n",
            "1114\n",
            "1115\n",
            "1116\n",
            "1117\n",
            "1118\n",
            "1119\n",
            "1120\n",
            "1121\n",
            "1122\n",
            "=== エラー内容 始 ===\n",
            "type:<class 'requests.exceptions.ConnectionError'>\n",
            "args:(MaxRetryError(\"HTTPConnectionPool(host='www.yonobi-love-it.tokyo', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7baecd4e80>: Failed to establish a new connection: [Errno -2] Name or service not known',))\",),)\n",
            "e自身:HTTPConnectionPool(host='www.yonobi-love-it.tokyo', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7baecd4e80>: Failed to establish a new connection: [Errno -2] Name or service not known',))\n",
            "=== エラー内容 完 ===\n",
            "1123 pass!\n",
            "1124\n",
            "1125\n",
            "1126\n",
            "1127\n",
            "1128\n",
            "1129\n",
            "1130\n",
            "1131\n",
            "1132\n",
            "1133\n",
            "1134\n",
            "1135\n",
            "1136\n",
            "1137\n",
            "1138\n",
            "1139\n",
            "1140\n",
            "1141\n",
            "1142\n",
            "1143\n",
            "1144\n",
            "1145\n",
            "1146\n",
            "1147\n",
            "1148\n",
            "1149\n",
            "1150\n",
            "1151\n",
            "1152\n",
            "1153\n",
            "1154\n",
            "1155\n",
            "1156\n",
            "1157\n",
            "1158\n",
            "1159\n",
            "1160\n",
            "1161\n",
            "1162\n",
            "1163\n",
            "1164\n",
            "1165\n",
            "1166\n",
            "1167\n",
            "1168\n",
            "1169\n",
            "1170\n",
            "1171\n",
            "1172\n",
            "1173\n",
            "1174\n",
            "1175\n",
            "1176\n"
          ],
          "name": "stdout"
        }
      ]
    }
  ]
}